/*ts-lint disable*/

// this file is autogenerated

export default [
  ['Chlorine gas', 'The Beatles', 'cityoil', 'Mary Mary', 'Desire Luzinda'],
  ['PCB', 'American pie', 'Kevin Hart', 'Cassette tape', 'Kenya Airways'],
  [
    'The good the bad the ugly',
    'City Oilers',
    'Solex padlock',
    'Sunset beach',
    'Eiffel tower'
  ],
  ['Bachwezi ', 'Beside', 'Phablet', 'Apollo Hotel', 'Door knob'],
  ['Golola Moses', 'Fala', 'kalita', 'The DAB', 'Trevor Noah'],
  [
    'Muchomo',
    'The dictator',
    'Ekitobero a la carte (double check that spelling)',
    'Kawempe',
    'Baseball'
  ],
  ['Nairobi', 'Kiwi', 'The River Nile', 'Video Library', 'NBA'],
  ['atin paco', 'Dexters Lab', 'Capital Shoppers promotion', 'Game', 'cell'],
  ['Olduvai gorge', 'Piatto', 'Night dancers', 'Roofings', ' Nefertiti'],
  ['Nile Special', 'System unit', 'Poker face', 'Fraud', 'SGS'],
  ['Landline', 'Mallet', 'Graphite', 'Karamajong', 'Jinja Town'],
  [
    'Beauty and the Beast',
    'Bamuda triangle',
    'Dumpy level',
    'Chips and chaps',
    'slabs'
  ],
  ['Cheese bread', 'WWE', 'Joe Bidden', 'Tetris', 'Swimming pool'],
  ['300', ' General Biraro', 'Buganda', 'Records', 'Cereal bowl'],
  [
    'Andrew Mwenda',
    'UPDF Special Forces Command',
    'roof',
    'Wrestlemania',
    'Chuck Noris'
  ],
  ['Snowden', 'Mountain Gorilla', 'Nankasa dance', 'Red Indians', 'Vitruvius'],
  [
    'land lord',
    'Sese gateway Beach',
    'Kanyamunyu',
    'Fantastic Four',
    'Edward Kale Kayihura'
  ],
  [
    'Greenland Bank ',
    'Fela',
    'Tamale mirundi',
    'Agnes Nandutu',
    'Milton Obote'
  ],
  [
    'Masaka road',
    'Power horse',
    'Lohnro Motors',
    'Presidential handshake',
    'Dairy farming'
  ],
  ['Kiss of death', 'interior design', 'Eddie Kenzo', 'Nissan', 'VGA'],
  ['plan A', 'The golf course hotel', 'Facebook', 'Kobil', 'Acholi'],
  ['Wavah water', 'Mombasa', 'Nasser', 'The omega', 'The Black Mambas'],
  ['Concentrate admixtures', 'metal plates', 'musisi', 'plan B', 'Bird flu'],
  [
    'Etofali',
    'Lugazi Sugar',
    'Donald Trump',
    'Selective reabsorption',
    ' Kisanja hakuna mchezo'
  ],
  ['Bungee jumping', 'Cineplex', 'Professor x', 'apartments', 'Protestant'],
  ['Muna Kampala', 'Ubuntu', 'Smart wire', 'Poker Face', 'Steve Jobs'],
  ['Inspector Gadget', 'Moi', 'Carbon copy', ' Meesi', 'Patrick idringi'],
  [
    'residence',
    'Nana hostel',
    'Internet explorer',
    'Ebee',
    'Amabere ya Nyinamwiru'
  ],
  ['Bunsen burner', 'Paul Walker', 'Amawulire', 'John 3:16', 'Cool cool bar'],
  ['Total', 'Benjamin Odoki', 'foremen', 'Nakasongola', 'Battery Low'],
  ['Carriage way', 'Gonja', 'Burkina Faso', 'Radio and Weasel', 'Rwanda'],
  [
    'Cardboard',
    'Iss',
    'The secret life of bees',
    'Michael Jordan',
    'engineers'
  ],
  ['UPC', 'Apple', 'Aerial', 'Sportsbet', 'Line of symetry'],
  [
    'Godfrey Massa',
    'Fanta Fruit Blast',
    'American dad',
    'Indian coolies',
    'Internet cafe'
  ],
  ['Sodium carbonate', 'Murchison falls', 'Drone', 'Muzungu', 'Vienna'],
  ['Ofwono bottle', 'Obote', 'Stephen Omony', 'Mufere', 'The Easter bunny'],
  ['Shakes Fimbo', ' Okocha', 'Iceland', 'architects', 'Uhuru'],
  [
    'Samurai',
    'Rig',
    'Buganda Road Primary School',
    'Colour schemes',
    'Pakalast'
  ],
  [
    "god's must be crazy",
    'Savero',
    'East African Reggae Bashment Crew',
    'Landrovers',
    'Music system'
  ],
  [
    'construction',
    'Tullow Oil',
    'Kurosaki ichigo',
    'CHOGM',
    'The Pearl of Africa'
  ],
  ['Gaeton Kagwa', 'Tripod stand', 'Kiwaani', 'Bean weavals', 'Nyama'],
  ['Nile Bank', 'plaster', 'DP', 'Raum', 'Autodesk'],
  ['Daudi Ochieng', 'Call of Duty', 'Badru Kigundu', 'Gaetano', 'Pintrest'],
  ['Lukaya', ' Cheops', 'Cool cool bar', 'Shrek', 'Shau Khan'],
  [
    'Dell optiplex',
    'A quality surveyor',
    'Land Cruiser',
    'Ggaba beach',
    'Denis Obua'
  ],
  ['Indian Ocean', 'city parents', 'Bake', 'Arua', 'Munyonyo'],
  ['pregnant', 'Union Jack', 'Iyingo', 'Mirinda fruity', 'Temangalo'],
  ['Kale Kayihura', 'Bantu', 'Ajono(Malwa)', ' Cleopatra', 'Kitengi'],
  ['casting', 'Head lamps', 'The undertaker', 'Sangoma', 'ufo'],
  ['Juliana Kanyomozi', 'Awillo Longoma', 'Zuena', 'Sudhir', 'Doom'],
  ['Daily Monitor', 'concrete', 'Jetlee', 'Pascal', 'Milk'],
  ['Copper rods', 'Wink', 'Pepe Kale', 'The observer', 'Luzira upper prison'],
  ['The embassy', 'Olympus has fallen', 'Scaffold', 'Jacob Oulanyah', 'Java'],
  [
    'Barcelona FC',
    'Uganda National Roads Authority',
    'Loubega',
    'Big size',
    'Tunisia'
  ],
  [
    'Gaetano kagwa',
    "The Assassin's creed",
    'Ben Kiwanuka',
    'Acacia Mall',
    'MTN'
  ],
  [
    'Leceister FC',
    'Uganda Revenue Authority',
    'Aristoc',
    'In heavens no beer',
    'naalya'
  ],
  ['The Kayola bus', 'Chicoco', 'Denzel', 'tanks', 'Lcd'],
  [
    'Fatboy',
    'National Water and Sewerage Corporation',
    'Kajjansi clays',
    'Semei Kakungulu',
    'mulindwa lawrence'
  ],
  ['Property agents', ' Akena', 'Kabaka Mwanga', 'manhole', 'Big O'],
  ['Dubai', 'Tea party', 'Agha Khan', 'Cisco', 'Nokia 3310'],
  [
    ' Onyango Obbo',
    'The ministry of education',
    'septic',
    'Mr. Waabit',
    'Clouds'
  ],
  [
    'Paka Paka',
    'Insurance broker',
    'Nursing',
    'Adobe master collective suite',
    'Hit man'
  ],
  [
    ' Goal line technology',
    'Speke resort munyonyo',
    'Mr. Kampala',
    'Doris Akol',
    'Facebook Messenger'
  ],
  [
    'Who killed captain Alex',
    'Poko poko',
    'Windows 3.1',
    'The world atlas',
    'Ray Charles'
  ],
  ['Kigali', 'Vacuum cleaner', 'Maggie Kigongo', 'PTSD', 'Pingu'],
  ['Uganda Martyrs⁠⁠⁠⁠', 'The Alchemist', 'The Nile crocodile', 'Ipsum', 'UEB'],
  ['Tororo Rock', 'UTL Mango', 'Lady Gaaga', 'The croods', 'Cinderella'],
  [
    'The flying squad',
    'Bugolobi Flats',
    'Ggaba beach',
    'A consul',
    '1900 Buganda Agreement'
  ],
  ['Mercedes SLR', 'Pokemon', 'face technology', 'Zero grazing', 'Katogo'],
  ['Kiwi', 'Fa', 'Kati Kati', 'Juba', 'Walumbe'],
  [
    'Makerere',
    'Wandegeya chicken',
    'Wizkid',
    'Sheebah Kalungi',
    'Janet Jackson'
  ],
  [
    'Nawab Asian Bistro',
    'Beast Wars',
    'Quality chemicals ltd',
    'FUFA',
    'Crane bank'
  ],
  [
    'EALA',
    'Ice ice baby',
    'Cleveland Cavaliers',
    'Gorillos',
    'Margaret Trowel school of fine art.'
  ],
  [
    'Kibimba rice',
    'Diarrhoea',
    'Spur',
    'Golden State Warriors',
    'Mwenge bigere'
  ],
  [
    'The Kampala casino',
    'Erias lukwago',
    'KK Security',
    'Irene brake',
    'Endingidi'
  ],
  [
    'Tony stark',
    'Kane and Abel',
    'iron bars',
    'Diski football',
    'Entebbe International Airport'
  ],
  ['Lady Cranes', 'Apple pie', 'KFC', 'Mwana-mujimu', 'Coco sisters'],
  [
    'Steven Kavuma',
    'Mukwano cooking oil',
    'Duracell',
    'Phone booth',
    'Club Play'
  ],
  ['Victoria University', 'Morgan Feeman', 'Fiji', 'Sekanolya', 'Buduuda'],
  ['Irene Namubiru', 'Water slide', 'Kampala Carnival', 'Everready', 'Kasese'],
  ['Auckland', 'Jada Pinket', 'Hewlett-Packard', 'Colgate', 'Adam Sandler'],
  ['An Apache', 'A design portfolio', 'Noor', 'Clock tower', 'Moreen kyalya'],
  ['Chicken Tonight', 'DHL', 'Hashtag Rap', 'Marie Antoinette', 'Brittania'],
  ['Brood', 'German shepherd', 'Edward Mutesa', 'The voice', 'rafters'],
  ['Sanyu FM', 'Wandegeya', 'Mohamad Ali', 'Barcelona', 'Kyambogo university'],
  ['HIV', 'Borosilicate', 'CECAFA 2010', 'KPMG', 'Grand theft auto'],
  ['Karamoja', 'Sugar daddies', 'Maso awo ', 'Shisha', 'Kisaasi'],
  ['plumbers', 'magnet', 'Jughead', 'Game nights', 'Kony'],
  ['Kabaka Mutebi', 'Atom', 'Lady and the Tramp', 'Y2K', 'Amakondeere'],
  [
    'Oryx',
    'marie curie',
    'World Wrestling Federation',
    'Samurai x',
    'Lugogo Bypass'
  ],
  [
    'City Oil',
    'Magnetic flux density',
    'Pemba Warriors',
    'PLE',
    'Every where you go'
  ],
  ['Nalufuka dance', 'Cannabis', 'Nido', 'Oil And petroleum', 'UPE'],
  [
    'An Intranet',
    'Kosovo',
    'Dictionary',
    'Texas Instruments',
    'The maple leaf'
  ],
  ['Boda boda', 'Extension cable', 'Luke Skywalker', 'Nakumatt', 'Chipoli'],
  [
    'Sheraton',
    'The Nile',
    '2001 Space Odyssey',
    'Grand imperial hotel',
    'Samosas'
  ],
  ['Downtown Owino', 'wolverin', 'Star Wars', 'Embooli', 'Pancakes aka'],
  ['King Fahd Plaza', 'Kalo', 'New Zealand', 'Ok Google', 'The Gaddafi mosque'],
  ['Apeta', 'Ludo', 'Mabirizi Complex', 'Namilyango College', 'Bogoya'],
  ['Wall clock', 'Uganda police', 'Kalo', 'War Dogs', 'Avocado'],
  [
    'Mosquitoe',
    'Greenlands Bank',
    'Ofwono',
    'Nawab Asian Bistro',
    'The Daily mornitor'
  ],
  ['Old taxi park', 'Sudhir Ruparelia', 'Picasso', 'Paddle', 'Katwe'],
  ['New taxi park', 'The alpha', 'Quencher', 'Margaret Thatcher', 'Fay'],
  ['Lord of the rings', 'ITunes', 'Namib desert', 'Jackie Chandiru', 'Google'],
  [
    'Kansanga Miracle Centre',
    'The Royal Guards',
    'Southampton.',
    'Silk Royale',
    'Uganda Telecome'
  ],
  ['Lake Albert', 'Katumba wamala', 'Salvador', 'Salim Saleh', 'Home run'],
  ['King Kong', 'Mr IBU', 'Sadolin', 'Henry Newton', 'KCCA carnival'],
  ['Kintu and Nambi', 'Taxi conductors', 'Allen Kagina', 'Sigiri', 'Bwaise'],
  [
    'Ewe',
    'The X factor',
    'Quality over quantity',
    'The Niagara falls',
    "Air Jordan's"
  ],
  [
    'Land of milk and honey',
    'Miley Cyrus',
    'Lady Gaga',
    'kakalambada',
    'The Joker'
  ],
  [
    'Kyadondo rugby grounds',
    'Sponge Bob',
    'Lebron James',
    'URA FC',
    'The ugandan air force'
  ],
  [
    'Uganda Broadcasting Corporation',
    'The smartphone network',
    'Mpenkoni',
    'Suicide squad',
    'Uganda airlines'
  ],
  ['Airtel', 'Serena', 'Nikon', 'Yoweri Kaguta Museveni', 'Air Uganda'],
  [
    'Standard chartered Bank',
    'Allan Kasuja',
    'SI unit',
    'Pioneer mall',
    'Fresh Dairy'
  ],
  ['Janet Museveni', 'Alex Ndawula', 'iTunes', 'City square', 'Wheat grains'],
  [
    'The national theatre',
    'Bebe Cool',
    "5 1/2' floppy disc",
    'Internet',
    'Honey moon'
  ],
  [
    'Kizza Besigye',
    'Gayaza high school',
    'Grip gloves',
    'Anglican',
    'Masaka-mbra highway'
  ],
  [
    'Inspector General of Government',
    'Kings college Budo',
    'Cairo',
    'Kasoli',
    'The friend zone'
  ],
  [
    'Bad black',
    'Macos',
    'Uganda national anthem',
    '9th October',
    'Sony bravia'
  ],
  ['Café javas', "St mary's Kitende", 'Smigo', 'William Obote', 'Kalooli'],
  ['Cheese', 'Panamera', 'Mountain Elgon', 'Friday the 13th', 'Youtube'],
  ['Bill Gates', 'Time traveller', 'Viber', 'Micheal Jackson', 'Owino market'],
  ['Dodo', 'Kira motors', 'Kilembe Mines', 'Kabale', 'The mummy returns'],
  [
    '24k magic',
    'Linux',
    'We Young Women and Men of Uganda',
    'West Nile tribe',
    'Kakira Sugar'
  ],
  ['Kings of Leon', 'Wine opener', 'Shakira', 'Kazinga Channel', 'Butabika'],
  ['Swangz Avenue', 'KFM', 'Alter wine', 'A submarine', 'Mt. Rwenzori'],
  [
    'Milutin Sredojević',
    'Volkswagen',
    'Anita Fabiola',
    'Peter and Jane',
    'Ekitaguriro dance'
  ],
  [
    'Judaism',
    'Northern bypass',
    'Robert Kiyosaki',
    'The Adventures of TinTin',
    'Irene ntale'
  ],
  [
    'Toyota Buffaloes',
    'Silver Springs Hotel',
    'Generations',
    'Marvin Gaye',
    'Uganda Airways'
  ],
  [
    'Salivary glands',
    'Fotogenix',
    'Club Ambiance',
    'Suits',
    'White water rafting'
  ],
  [
    'Hajji Nasser ntege Ssebagala',
    'Idi Amin Dada',
    'Mean Machine',
    'Addidas',
    'Jinja'
  ],
  [
    'Gameboy color',
    'Kira Motors',
    '50 First Dates',
    'Humps ahead',
    'Samsung galaxy'
  ],
  ['Bull', 'Doctor', 'Agwara', 'Aerospace engineering', 'The pyramids'],
  [
    'Jessica Alba',
    'Dorcus Inzikuru',
    'The Republic of Kenya',
    'African crafts',
    'Kanye West'
  ],
  [
    'Hwansung furniture',
    'Ennanga',
    'Oil refinery',
    'Cham Towers',
    'Parliament Avenue'
  ],
  ['Power FM', 'Lex Luther', 'Ugali', 'Diskette', 'Kazire'],
  [
    'Makerere university',
    'Noddles',
    'Bat valley theatre',
    'Lake Malawi',
    'Shell'
  ],
  ['Hi vis vest', 'The Ssese islands', 'Speed bumps', 'AON', 'Muzikiti'],
  [
    'Ronald Reagan',
    'La Pattisserie',
    'Spectrum',
    'Caster Semenya',
    'Leonardo di Caprio'
  ],
  ['The East African', 'Besigye', 'Monot', 'Wallstreet', 'Aronda nyakairema'],
  ['Fila', 'Kasangati', '91.3 capital fm', 'Forex exchange', 'Fragrance'],
  ['Knights', 'Janan Luwumu', 'Omweso', 'Lake Kagera', 'The kyoola solar bus'],
  [
    'Kericho Tea',
    'Early man',
    'Snakes and ladders',
    'Bugs Bunny',
    'Capital Shoppers'
  ],
  ['Cassava', 'Poker face', 'Simba FC', 'Malaba', 'Toyota'],
  [
    'Kasubi tombs',
    'Inzkuri',
    'Martial arts',
    'Magufuli',
    'Double glazed glass'
  ],
  [
    'Moses Ndiema Kipsiro',
    'Napoleon Bonaparte',
    'Rukidi IV of Toro',
    'Game of thrones',
    'Grocery store'
  ],
  ['Ubc', 'Maradona', 'FDC', 'Shaka Zulu', 'Crazy Cock'],
  [
    'Nice Biscuits',
    'The Department of justice',
    'Mehta',
    'Fresh diary',
    'Ssanyu FM'
  ],
  ['And1', 'Chair cushions', 'Sudhir Ruparelia', 'Go cart racing', 'Dfcu bank'],
  ['Milkman', 'Special effects', 'Kanungu', 'Scribes', 'Nokia katochi'],
  ['Tip Top Bread', 'Migingo Island', 'ABBA', 'Valentine', 'Kitoko'],
  ['Renault', 'Phantom zone', 'Lakwena', 'GoTv', 'Kowtow in your poohoo'],
  ['Ne-yo', 'Uganda Silverbacks', "Okot p'Bitek", 'Huawei', 'Cameroonian'],
  ['USSR', 'The hobit', 'Tuskys', 'Maurice Kirya', 'Endongo'],
  [
    'Horse shoe',
    'things fall apart',
    'Charles Darwin',
    'CCCC',
    'Kisoro district'
  ],
  [
    'Village Mall',
    'The lion king',
    'The Dukka',
    'Uganda railway',
    'Mt muhavura'
  ],
  [
    'Sphincter muscles',
    'Song of Lawino',
    'SMACK',
    'Rav4',
    'Certificate of appreciation'
  ],
  [
    "Communication's House",
    'Janet Kataha Museveni',
    'Caffesserie',
    'Madagascar',
    ' The great Pyramids of Giza'
  ],
  ['Multichoice', 'Jeniffer Musisi', 'Gaddafi', 'MySpace', 'Africa'],
  [
    'Stephen Curry',
    'Seya ',
    'Midcom',
    'Emmanuel Tumusime Mutebile',
    'The Hulk'
  ],
  [
    'zari',
    'Daffy Duck',
    'Canon',
    'Kampala International University',
    'Vj jingo'
  ],
  [
    'Rwenzori Mountains',
    'Luzira',
    'Bella Wine',
    'Kampala Cocktail Week',
    'Mulago hospital'
  ],
  [
    'Oasis mall',
    'Sleeping sickening',
    "Kabaka's Lake",
    ' David Beckham',
    'Nakasero blood bank'
  ],
  ['Nancy Drew', 'Olx Uganda', 'Arse', 'Lake Victoria', 'Firebase'],
  ['Margarine', 'Siri', 'Nakasero Primary School', 'The Kyabaziga', 'Isuzu'],
  [
    'The London eye',
    'Lake Kyoga',
    'Nice house of plastics',
    'Weed',
    'Namirembe Cathedral'
  ],
  [
    'Lake Bunyonyi',
    'Ange noir',
    'ISIS',
    'Muhammad Santur (spelling)',
    'Ssese Islands'
  ],
  [
    'Guvnor Night club',
    'Arabica coffee',
    "Dr. Shaque O'Neal",
    'Kalangala',
    'Club silk'
  ],
  [
    "G4s McDonald's",
    'The Ministry of Education and Sports',
    'Monalisa',
    'Street art',
    'BETWAY'
  ],
  ['Google maps', 'Tamarai', 'Emperor Olando', 'Mweya safari lodge', 'Midcom'],
  [
    'Centenary Park',
    'Mamdani',
    'Fang Fang restaurant',
    'Kakande',
    'Ekyimbeewo'
  ],
  ['Déjà vu', 'Kololo airstrip', 'Kawunda suit', 'FUBA', 'Fizzy drinks'],
  ['Delta air', 'Hima cement', 'Posho and beans', 'samsung', 'Mengo'],
  ['Nandos', 'Akamwesi hostel', 'Shaggy', 'Bbale Francis', 'Telefunken'],
  [
    'Full beam lights',
    'Lugogo Cricket Oval',
    ' Anslem',
    'Entebbe International Airport',
    'Sir Alex Ferguson'
  ],
  [
    'Usher Reymond',
    'Steven Spielberg',
    'TV chicken',
    'KIU Titans',
    'Microsoft'
  ],
  [' Ronaldo', 'Rolex', 'KCCA FC', 'The Kampala sun', 'Country music'],
  ['Jesa', 'Express FC', 'Bush Court', 'Molokony', 'KIU'],
  ['Forest Mall', 'Kato Lubwama', 'Angelina Jolie', 'Hot loaf', 'Lugogo Mall'],
  [
    'Public sensitisation',
    'Bob Marley',
    'Mambo number 5',
    'Bushera',
    'Sony Walkman'
  ],
  [
    'Seychelles',
    'Rift valley railway',
    'Quatar airways',
    'A Chariot',
    'Kendrick Lamar'
  ],
  ['Spock', 'Quality Supermarket', 'Teso', 'Dunhill', 'Carpool'],
  ['Abuja', 'Table mats', 'Dunlop', 'Arusha', 'Garden Tea'],
  ['UNRWA', 'Ekizino dance', 'Shoe', "King's College Budo", 'Channel O'],
  ['Cherokee', 'CBS', 'Gap year', 'The nervous system', 'Life Buoy'],
  ['Kafuunda', 'Namagunga Secondary', 'mukiibi lawrence', 'To Expire', 'Navio'],
  ['Vienna College', 'Katanga', 'Chameleon', 'Gnl', 'Gen Katumba Wamala'],
  ['Mamba', 'Samuel L. Jackson', 'Merry-go-round', 'Kawunyemu', 'Paul kafeero'],
  [
    'Zambian President',
    'Shimoni Primary Shool',
    'Popcorn',
    'Mosese Magago',
    'Shaulin soccer'
  ],
  [
    'Indiana Jones and the Last Crusade',
    'Godrey Binaisa',
    'CNN',
    'Debanj',
    'Kadongo Kamu'
  ],
  [
    'Namboole Stadium',
    'Tip Top Bread',
    'Wolokoso',
    'Oxygen',
    'The Republic of Tanzania'
  ],
  [
    'Sama-saulting chicken',
    'Austraia',
    'Ebola',
    'The Democratic Republic of Congo',
    'TVO'
  ],
  ['Nvidia graphics card', 'Juventus', 'Omo', 'Black Mamba', 'Kigali'],
  [
    'Toyota Vitz',
    'Flamingo',
    'Sonic the Hedgehog',
    'Polygamy',
    'Brazilian hair'
  ],
  ['Barkcloth', 'Fake hair', 'Spear Motors', 'Teletubbies', 'The Serengeti'],
  ['UNEB', 'Guard rail', 'Weetabix', 'The Sun', 'Aristoc'],
  ['Beautiful mess', 'Capital FM', 'Endere', 'Soulja Boy', 'Bhagdad'],
  ['KLM', 'PPDA', 'Pittsburgh steelers', 'Coach Carter', 'Rwenzori'],
  [' Music dance and drama', 'Spa', 'Port Malaba', 'Ntinda', 'Puss in boots'],
  ['Mubs', 'Eagles band', 'Blue 3', 'Zanzibar', 'Coffee shop'],
  ['The Simpsons', 'Traffic jam', 'Angels and Demons', 'Polo', 'Dar-es-salaam'],
  ['Winterland', 'Wakaliwood', 'Fort Jesus', 'Dubai', 'NASA'],
  ['Stone Town', 'Diamonds', 'Saint', 'Arusha', 'Passengers'],
  ['Woodball', 'Ngongoro Crater', 'Macintosh', 'Golf', 'Zinjanthropus'],
  [
    'Kitante Primary School',
    'Zoom Club',
    'Blu-ray disc',
    'Queen Elizabeth',
    'Mukene'
  ],
  [
    'Matatu',
    'The exodus',
    'Sadolin paints',
    'Long horned cattle',
    'The great trek'
  ],
  ['Kampala Parents school', 'Mufasa', 'Vernier caliper', 'Jet ski', 'Lenovo'],
  [
    'Uganda cancer institute',
    'Santa',
    'Scratch proof',
    '2016 Presidential elections',
    'Ear plugs'
  ],
  [
    'The Genesis',
    'Cumulative frequency',
    'Age of empires',
    'Special forces command (SFC)',
    'Mega Standard Supermarket'
  ],
  ['The Globe', 'Baakisiima dance', 'UNRA', 'MTV', 'Christians'],
  ['Marco Polo', 'Photoshop', 'Irongo dance', 'Constantine', 'Jim Muhwezi'],
  ['BomberMan', 'MoneyGram', 'Pedlum Bob', 'Tamenaibuga dance', 'Four cousins'],
  [
    'Iris',
    'Mwanga dance',
    'Mozart Wolfgang',
    'Mountain Moroto',
    'Akembe dance'
  ],
  ['Portbell', 'Chinese', 'Runyege and Entongoro dance', 'Beams', 'NTV'],
  ['Quencher', 'Pick n Peel', 'Bruce Lee', 'Bwola dance', 'Adungu'],
  ['Ak-47', 'Tunis', 'LinkedIn', 'Klashvinkov', 'TATA'],
  ['Linkin park', 'Uzi', 'NFL', 'Source of the nile', 'Jik'],
  [
    'Donkey Kong',
    'Nile casino',
    'NBA 2016',
    ' Kaihura nkuba',
    'The accountant'
  ],
  [
    'Mouse trap',
    'Mosquitoes',
    'Stone Cold Steve Austin',
    'Binding wire',
    'Casablanca'
  ],
  ['The Jackson Five', 'Poker', 'Last king of Scotland', 'Netflix', 'Monopoly'],
  ['Louvres', 'Nandujja', 'Timothy', 'Oseke', 'Mukwano'],
  [
    'Jacob',
    'Ventilated improved pit latrines',
    'Catholicism',
    'Wilson',
    ' Another rap'
  ],
  ['Haka', 'Cadbury', 'Kibwetere', 'Micho ', 'Mitsubishi'],
  ['Luwombo', 'Whore', 'Animaniacs', 'Designated survivor', 'Gadafi'],
  ['Samsung galaxy note 4', 'Ford', 'St. Augustin', 'Dexter', 'Kikomando'],
  [
    'Century Cinemax',
    'Friday nights live',
    'The blood moon',
    'Will Smith',
    'Bungee jumping'
  ],
  ['Mandazi', 'columns', 'Maths', 'Posho', 'Red Carpet'],
  ['Tusker project fame', 'Sprint', '4G', 'Kings of Leon', 'Lubiri'],
  [
    'Whatsapp',
    'Shaggy',
    "That's Life Mwatu",
    'Burger King',
    'Rock Paper Scissors'
  ],
  ['Pombe', 'Bruce Willis', 'Typhoid', 'The standard gauge railway', 'Windows'],
  [
    'Micro SD card',
    'Mediterraneo Restaurant',
    'Usain bolt',
    'The davinci code',
    'Liquid Silk'
  ],
  ['Pete Sampras', 'Scotch', 'Rotten Tomatoes', '1 Million', 'Pimp'],
  ['Guvnor', 'Ludo', 'Condom', 'geoffrey massa', 'Sound of music'],
  [
    'Liquid soap',
    'Adungu dance',
    'Muhammad Ali',
    'Mozambique',
    'State minister'
  ],
  ['Evander Holifield', 'Cake', 'Vintage cars', 'Back hoe', 'Diarrhoea'],
  [
    'Simplex network',
    'Uganda Management Institute',
    'Red',
    'Club Amnesia',
    'Manchester united'
  ],
  ['Lever', 'Bedbug', 'Tecno', 'African Cup of Nations', 'Pompeii grill'],
  [
    'Barclays Bank',
    'Winter',
    'Kyadondo Rugby Club',
    'TASO',
    'The grasshopper month'
  ],
  [
    'Ms DOS',
    'Camouflage',
    'Remote',
    'Lithium ion batteries',
    'Lake View Hotel'
  ],
  ['GPS', 'Rugby', 'Service duct', 'Alshabaab', 'Terms and conditions'],
  ['Lilian Mbabazi', 'Betty kamya', 'Jack fruit', 'Nike', 'Garlic stew'],
  ['Betway Kobs', 'Easter Monday', 'Corolla', 'Hima Cement Heathens', 'NBS'],
  [
    'Fitness trackers',
    'Air guitar',
    'Fastjet',
    'Mozilla',
    'Kevin Systrom and Mike Krieger (instagram founders)'
  ],
  ['Rwot Kweri', 'Lama', 'Jimmy Enabu', 'Idi Amin', '350 mls'],
  ['YMCA', 'Kiira EV', 'Tv Africa', 'Brian Odong', 'Friday Night Lights'],
  [
    'HP',
    'Tito Lutwa',
    'Honda',
    'A company profile',
    'The Source of the River Nile'
  ],
  [
    'Terminator',
    'Ethiopian Airways',
    'Government aided schools',
    'Kidepo national park',
    'Aladdin'
  ],
  ['Ugly Betty', 'George of the Jungle', 'Lights', 'Malwa', 'Snowwhite'],
  ['Neon', 'Fly540', 'Animal farm', 'pipes', 'University professor'],
  ['Jacuzzi', 'Nakasero market', 'Iron ore', 'Macarena', 'Wbs'],
  [
    'Agataliko Nfuufu',
    'Hey there Delilah',
    'Timber',
    'Dead shot',
    'Ultrasound machine'
  ],
  [
    'Italia',
    'Martin Luther King',
    'The synagogue church',
    'Sweet Pepsi',
    'Uber'
  ],
  ['Albert Einstein', 'The hostel', 'Telephone', 'The Etihad', 'Nail clippers'],
  [
    'Mabira forest',
    "Art's students",
    'Water proof',
    '9 lives',
    'Handle with care'
  ],
  ['ISU', 'Jazz Supermarket', 'Blind spot', 'Habari', 'Big Brother Africa'],
  ['Mnet', 'Lagos Naija', 'Browser history', 'Postbus', 'Robert Downey junior'],
  ['Startimes', 'Lamy', '256', 'Coffee spirit', 'Wireless Fidelity'],
  [
    'Nursery rhymes',
    'Curfew',
    'Bbale Francis',
    'Bismilah',
    'ABSA premier league'
  ],
  [
    'How I met your mother',
    'Kabalagala',
    'Kodak',
    'Ginger bread',
    'Bruno Mars'
  ],
  ['Stanley Ntagali', 'Nasser rd', 'Subaru', 'Kyanja', 'Bed wetters'],
  [
    'Forest',
    'Kampala International School Uganda',
    'Semliki National Park',
    'Highland water',
    'Bugolobi'
  ],
  ['Otafire', 'Nile Perch', 'Naguru', 'Leverage', 'Fly on your own'],
  [
    'Xfm',
    'Google drive',
    'The School uniform',
    'To engrave and embroid',
    'Tommy Hilfiger'
  ],
  ['DFCU', 'Nakasero', 'Zumba', 'January', 'Acer'],
  [
    'The rich also cry',
    'December',
    'Noise proof',
    'Gaetano Kaggwa',
    'Kimberly mines'
  ],
  [
    'Kampala Carnival',
    'Nokia',
    'Telegram',
    'Kampala Restaurant Week',
    'The Ministry of Foreign Affairs'
  ],
  [
    'Middle East consultants',
    'The Pearl Guide Uganda',
    'Dr. Bosa',
    'Supersport Blitz',
    'Uganda National Bureau of Standards'
  ],
  [
    'Black bell',
    'Sony vaio',
    'Floor traps',
    "As thin as radio's arms",
    'Mirror'
  ],
  ['Calculators', 'Mulwana empire', 'Handle', 'Weetabix', 'Microsoft Xbox'],
  [
    'The goatee',
    'The adventures of Tom Sawyer',
    'Metroplex Naalya',
    'Princes Diana',
    'Uhuru Kenyatta'
  ],
  ['Wisdom tooth', 'OO7', 'Muwogola dance', 'Kampala golf course', 'Picfare'],
  [
    'Karate Kid',
    'Transcend',
    'Umoja',
    'Julius Nyerere International Airport',
    'Woolworth'
  ],
  ['Lamp post', 'Precision Air', 'Enkwanzi', 'Bell lager', 'Lake Tanganyika'],
  ['Gold', 'Christian fellowships', 'Botanical gardens', 'Huawei', 'Geisha'],
  ['Royco', 'Daniel Arap Moi', 'Tropical Heat', 'Orient Bank', 'KIA'],
  ['Boxers', 'Super Dip', 'Gym', 'Mitsubishi', 'Uganda House'],
  ['Pajero', 'Maputo', 'Nissan Patrol', 'Clark Kent', 'Kikumi kikumi'],
  [
    'Basoga',
    'Toyota Corolla',
    'A burger meal',
    'Subaru Forester',
    'HTC phones'
  ],
  ['Subaru Imprezza', 'Ankara', 'Kick boxing', 'Accra', ' Cristiano Ronaldo'],
  ['3D printer', 'Reebok', 'Adolf Hitler', 'Hewlett Packard', 'Mr Bean'],
  ['Good year', 'Mission Impossible', 'Coffee mug', 'Israel', 'Stanbic Bank'],
  [
    'Chief begger',
    'The arsenal massacre',
    'Greenland',
    'Ghetto President',
    'Methane gas'
  ],
  ['Power puff girls', 'Wanale', 'Express FC', 'Mirinda', 'National language'],
  [
    'Ferry',
    'Nice clear',
    'London has fallen',
    'Oxford Mathematical Set',
    'Air force one'
  ],
  ['Casio', 'The avengers', 'Kampala', 'Case clinic', 'Land mines'],
  ['Club Venom', 'Arsene Wenger', 'Dwayne Johnson', 'magma', 'Bill Gates'],
  [
    'R. Kelly',
    'Black Swan',
    'Kansanga',
    'Legos',
    'Rwabushenyi Memorial Chess Championship'
  ],
  [
    'Rwenzori Mineral Water',
    'Uganda Chess Federation',
    'Uganda Waragi',
    'Winnie Nwagi',
    'Phanero'
  ],
  ['family guy', 'Sauti Sol', 'John Akii-Bua', 'Mega milk', 'Barber Shop'],
  ['Mine Boy', 'The hub', 'Spearmint', 'Robert Mugabe', 'Bobi wine'],
  ['Jacob Zuma', 'soak pit', 'Bata', 'Paintball', 'Tsetsefly'],
  ['Splash', 'Vulnerable persons', 'Flea', 'Spalding', 'Dmark'],
  [
    'Rwakitura',
    'Kabaka Mwenda Mutebi II',
    'Obey your thirst',
    'Stick bread',
    'Taste the feeling'
  ],
  [
    ' Game night is fun',
    'Everywhere you go',
    'Lumia',
    'South Sudan',
    'Mahatma ghandi'
  ],
  ['Unilever', 'Stella Nyanzi', 'Reggae music', 'M23 rebels', 'Jomo Kenyatta'],
  [
    'The 9th of October',
    '[22:13, 2/27/2017] +256 702 204609: Logitech',
    'Mohamad Nseroko',
    'Aliko Dangote',
    'The Mercedes Benz'
  ],
  ['Chuck Bass', 'Iron bar', 'Vim', 'Mediterranean Sea', 'Phillips'],
  ['Grip gloves', 'Ugly Duckling', ' Onyango', 'Instagram', 'Auto correct'],
  ['otada', 'Hair dye', 'Raka raka dance', 'The Swiss alps', 'Malaria'],
  [
    'The championchampions league',
    'LinkedIn',
    'Pillows',
    'Mark Zuckerberg',
    'The French Revolution'
  ],
  ['Steve Jobs', 'Goodnight', 'Ducati', 'Amazon Kindle', 'Prado'],
  [
    'James bond',
    'Reid Hoffmann (LinkedIn founder)',
    'Adding machine',
    'Evan Spiegel (snapchat founder)',
    'Eddy Murphy'
  ],
  ['Street Fighter', 'Jarvis', 'Siri', 'Bullet proof vests', 'Kadashians'],
  ['Bank robbers', 'Looney Tunes', 'Esau', 'Barack Obama', 'Cable carts'],
  ['Justin Beiber', 'Ninja worrier', 'conductor.', 'Leica', 'Vladimir Putin'],
  [
    'The acacia place',
    'Pokemon',
    "Chameleon's tongue",
    'Digimon',
    'kololo airstrip'
  ],
  [
    'The Mighty Morphin Power Rangers',
    'iPhone 7',
    'Beetleborgs',
    'The Big Five',
    'Ktv'
  ],
  ['The green light', 'Queen of katwe', 'A blogger', 'State house', 'Omo'],
  [
    'Uganda Telecom',
    'Uganda Coffee Development Authority',
    'Bald',
    'Kiboko',
    'Sansa'
  ],
  [
    'Specioza Kazibwe',
    'Simba Telecom',
    'Alien ware',
    'Ice age',
    'Speke apartments'
  ],
  [
    'Captain Planet',
    'Hotel Africans',
    'Mt Kenya',
    'Watoto Church',
    'Fanta Fruity'
  ],
  [
    'Boda',
    'Kifeesi',
    'Dead party',
    'Hoover craft',
    'Uganda Manufacturers Association'
  ],
  [
    'A walk in closet',
    'Door stoppers',
    'Mandazi',
    'Pope John Paul II',
    'Sweat glands'
  ],
  ['Mouse traps', 'Fifa 2016', 'Uganda cranes', 'Kiprotich', 'Justice league'],
  ["Sula's rolex", 'Work work work work', 'Butcherman', 'Kobs', 'Godzilla'],
  ['Happy hour', 'Garden Tea', 'Made in china', 'Trash talker', 'Polar bears'],
  [
    'Nail polish',
    'Theatre la Bonita',
    'Celtel',
    'Planet of the apes',
    'John speke'
  ],
  [
    'Namboole',
    'Saida Kaloli',
    'The ten commandments',
    'Canoes',
    'NDA (non disclosure agreement)'
  ],
  ['Lido Beach', 'Value added tax', 'Isis', 'Wrist watch', 'Tyson Waragi'],
  ['Interior designers', 'Premio', 'Kwagalana group', 'Burundi', 'Nokia tune'],
  [
    'Halima',
    'Highland mineral water',
    'Nze Nimiro',
    'Punch cards',
    'Pool Court'
  ],
  [
    'Plot number and block number',
    'Jackie chan',
    'Miya farouk',
    'Davis and Shirtliff',
    'This side up'
  ],
  [
    'Sebagala and Sons',
    'The Common Markets for East and Southern Africa (COMESA?)',
    'Gators Cafe',
    "Valentine's day",
    'Pope John Paul the 2nd'
  ],
  ['Night soil', 'Mt Kilimanjaro', 'Theodolite', 'Ruhakana Rugunda', 'KIA'],
  ['Patrick Mbire', 'Akamba', 'Core', 'Scrabble', 'Mumbere'],
  ['Saudi Arabia', 'Riham biscuits', 'Super dip', 'Iron bar thugs', 'Beyoncé'],
  [
    'Garden city',
    'Cairo international bank',
    'Namugunga',
    'Jehover witness',
    'Queen bee'
  ],
  [
    "Don't be like bro",
    'Aristoc',
    'Bad Brown',
    'The New Vision',
    'Nintendo 64'
  ],
  [
    ' Light and sound show',
    'A Wish list',
    'One by one',
    'Gps Coordinates',
    'Night prep'
  ],
  [
    'Saala Puleesa',
    'Black sheep affair',
    'Navigator',
    'Spiderman',
    'The East African Community'
  ],
  [
    'Superman v Batman',
    'Cheat codes',
    'The Lego movie',
    'Ssebagala and sons electrical supplies',
    'Stage (as in boda or taxi stage)'
  ],
  [
    'Paul Kagame',
    'Hypocritical analysis',
    'Rwenzururu',
    'Chuck Norris',
    'Bonjour ( total shops)'
  ],
  [
    'Al Shabbab',
    'Lagos',
    'Joseph Mabirizi',
    'Hewlett Packard',
    'The Ministry of Health'
  ],
  ['Mapeera house', 'JFK', 'Paint specifier', 'Musaawo', 'Snapchat'],
  [
    'Ykee Benda',
    'Binding tape',
    'Silicon chips',
    'Hipsters',
    'Florescent tubes'
  ],
  ['Tesla', 'Neyo', 'Gaz', 'Renault', 'KPC'],
  ['Karuma', 'Sony Ericsson', 'Rebecca Kadaga', "Worker's House", 'Lake kyoga'],
  ['Game stores', 'Intern doctors', 'Reptiles', 'Boxing gloves', 'Mutation'],
  ['Yusuf Lule', 'Cheer leaders', 'Bujagali Falls', 'Wine cork', 'Bell Lager'],
  ['Mississippi', 'Plot', 'Phillips', 'Emirates stadium', 'Ghost busters'],
  ['Etihad stadium', 'Engalabi', 'Zone 7', 'Ugandan girls', 'SC Villa'],
  ['Broke', 'Ketchup', 'Science students', 'Bendicto Kiwanuka', 'A wordrobe'],
  [
    'Chris Adams',
    'Ivory Tower',
    'Busy signal',
    'Snow white and the seven dwarfs',
    'Kintu'
  ],
  [
    'Afcon',
    'Morgan Trainer',
    'Clay pots',
    'Nakawunde',
    'Rainbow International School'
  ],
  [
    'Sugar mommies',
    'Swissgarde',
    'Nike frees',
    'Teenage Mutant Ninja Turtles',
    'Marabu stork'
  ],
  [
    'Stratosphere',
    "Saint Mary's Kisubi",
    'All Saints Cathedral',
    'Hannah Montana',
    'Habari , kabi , danger'
  ],
  ['King Shaka', 'North bridge', 'Blu 3', 'AIDS', 'Christian Bale'],
  ['The QWERTY', 'Emirates', 'UV rays', 'Judith heard nalongo', 'Sticky keys'],
  ['Anne Kansime', 'Bon Apetit', 'Ludacris', 'South Sudan', 'BBC'],
  [
    'Double A batteries',
    'Roke Telekom',
    'Christmas',
    'Larakaraka',
    'Green star'
  ],
  [
    'James corden',
    'The North Star',
    'Piato',
    'PAC (public accounts committee)',
    'ABSA'
  ],
  ['CPU', 'Caterpillar', 'Akadinda', 'Series Channel', 'Sekitulege'],
  ['Daddies', 'Education', 'Isaac Newton', 'Star fish', 'Jinja road'],
  ['Centenary Bank', 'Hallmark', 'Alteeza', 'BET', 'Spacio'],
  [
    'E! Entertainment',
    'Betty Nambozi',
    '[16:05, 2/27/2017] +256 702 204609: 9th October 1966',
    'Nssf',
    'Morogoro'
  ],
  ['Zara', 'Jumia', 'Mobile money', 'Back hoe', 'Pope Francis'],
  [
    'Yosemite Sam',
    'Reset button',
    'Boys 2 Men',
    'The Dark Knight',
    'Shopping voucher'
  ],
  ['Cartoons', 'NRM', 'Human trafficking', 'Eminem', 'Mt. Elgon'],
  ['Ziggy Marley', 'Kobe Bryant', 'Dasani', 'Owen Falls Dam', 'Mars'],
  [
    'Chameleone',
    'Insomnia',
    'Solar Eclipse',
    'Gordon Wavamuno',
    '1000 ways to die'
  ],
  ['Pablo Escobar', 'Pirelli', 'Malaria', 'Tutankamun', 'Wedding Meeting'],
  ['Giggles', 'Omo', 'Transistor', 'Mutaasa Kafeero Plaza', 'Mark x'],
  ['A Locket', 'fabrication', 'Detol', 'Napoleon Bonaparte I', 'Mount Kadam'],
  ['Balokole', 'Big G', 'Goliath', 'Orbit chewing gum', 'King Oyo'],
  ['PK', 'Flu shots', 'U-turn', 'Washing machine', 'Afrobasket Championships'],
  ['A Rolex kiosk', 'Rock Boom', 'Water purification', 'kakise', 'Safe boda'],
  ['Invaka Trump', 'Guard rail', 'Muvule Tree', 'Sodium', 'Mccauley Culkin'],
  [
    'A flight simulator',
    'Home Alone',
    'Bible house',
    'Owl city',
    'Chinue Achebe'
  ],
  [
    'Michael Jackson',
    'Balck boards',
    'Heathens',
    'The Geneva peace convention',
    'Friendship taxi'
  ],
  ['Woolworths', 'Earth, Wind and Fire', 'Game zone', 'Delident', 'Yaka'],
  ['AC Milan', 'Public holiday', 'Backtrack', 'Sky diving', 'Inter Milan'],
  [
    'Teenage Mutant Ninja Turtles',
    'Easter Monday',
    'The us navy seals',
    'Sega Mega Drive',
    'Mulago referral hospital'
  ],
  [
    'Sega Dreamcast',
    'Invisible children',
    'Sheebah',
    'Goloola Moses',
    'Java House'
  ],
  ['Bukedde TV', 'Sony Playstation', 'Angry birds', 'Tilapia', 'Bay watch'],
  ['Rwandair', 'Energizer', 'Jukebox', "The LRA's Kony", 'Monica Lowinsky'],
  [
    'Lexus',
    'Jean Claude Van Damme',
    'Bridal magazine',
    'Ham Towers',
    'Australia'
  ],
  [
    'Bob Marley and the Wailers',
    'Need for speed',
    'Jackie Chan',
    'Owen falls dam',
    'Bujagali falls'
  ],
  [
    'The big bang',
    'Pablo',
    'Fresh Prince of bellair(not sure of the spelling)',
    'EAC',
    'Cumlo-nimbus clouds'
  ],
  ['Africell', 'Cortana', 'Syschelles islands', 'Graduation gouns', 'Chapati'],
  [
    'Bic',
    'Sitting at the high table',
    'Bakayimbira Drumactors',
    'Wembley stadium',
    'Robbin island'
  ],
  [
    'Civil aviation authority',
    'Motherboard',
    'Morgue',
    'Kangaroo jack',
    'Soweto'
  ],
  ['Previously on', 'The prison break', 'Bukoto Flats', 'Mun G', 'Mauritania'],
  ['Purple Rain', 'Sweat glands', 'Chelsea FC', 'Endometriosis', 'Ihk'],
  [
    'Mohhock',
    'Internet bundles',
    'We will not wait for karamoja to develop',
    'PCL',
    'The northern by-pass'
  ],
  [
    'False prophets',
    'Haris international',
    'COMESA',
    'Holy Communion',
    'Virtual reality gear'
  ],
  [
    'Tigerhead',
    'Kabira country club',
    'Cold play',
    'Linen cloth',
    'Low battery'
  ],
  ['Snake', 'Kenyatta', 'xmen', 'Crested Crane', 'Kaloodo'],
  ['Kamyu', 'Kitkat', 'Nail clipper', 'Illusions', 'The leopard'],
  ['Lake katwe', 'White ants', 'Buglar proofing', 'Snap chat', 'Kcca'],
  ['Forex Bureau', 'Guitar', 'The notebook', 'Pneumonia', 'Bruce Lee'],
  [
    'Chikomando',
    'Vuzu Tv',
    'Smart boards',
    'Rick dees and americas top 40',
    'Landscape artists'
  ],
  [
    'Cool cool bar',
    'Spelling bee',
    'Pay as you earn',
    'Proton',
    'Mulnutrition'
  ],
  [
    'Chief Executive officer',
    'Anger management',
    'Red Bull',
    'Kofi olomide',
    'Bed bugs'
  ],
  ['Sharpie', 'Pelican', 'Bony katatumba', 'Glazing', 'Old is gold'],
  ['EPL', 'Psquare', 'Autumn', 'Reaching heights', 'Police pickup'],
  [
    '[22:55, 2/27/2017] +256 773 106724: Community policing',
    'Crime preventers',
    'Live stalk farming',
    'Enteebe',
    'Abraham'
  ],
  ['Othello', 'Mechanised systems', 'The Bistro', 'Red Banton', 'Spellings'],
  [
    'Queen Latifa',
    'SADC',
    'The Haunted Hathaways',
    'The Mexico-usa border',
    'Beans'
  ],
  [
    'Igongo cultural centre',
    'Plastic smiles',
    'Chapatti',
    'Solar cell',
    'Wine'
  ],
  [
    'Central business district',
    'Chicken brain',
    ' Kowtow in their poohoo',
    'Chocolate syrup',
    'Second Chance'
  ],
  [
    'White water rafting',
    'Kitugum',
    'Raila Odinga',
    'East African development bank',
    'Arsenal FC'
  ],
  ['The omuzinga', 'Asus', 'Equity bank', 'Olanya Colombus', 'Polygamy'],
  [
    'Winter is coming',
    'Mama Fiina',
    'Wanchekecha',
    'Shoprite',
    'Uhuru kenyatta'
  ],
  [
    'Arnold Schwarzenegger',
    'The Daily Monitor',
    'Rush Hour',
    'Oliver Twist',
    'The Ebonies'
  ],
  [
    'Rice porridge',
    'The super bowl',
    'Kololo',
    'Gattomato',
    'Fixed deposit accounts'
  ],
  ['UB40', 'Breakfast and bed', 'Sugar cubes', 'Bukedde', 'Bull shit'],
  [
    'The Ministry of Finance',
    'Pit latrine',
    'Jose Morinho',
    'Hipster',
    'Uganda clays'
  ],
  [
    'Animal hides',
    'Red Pepper',
    'John Magufuli',
    'Stucco paint',
    'Salt shaker'
  ],
  ['Checkers', 'Barclays', 'Honey combs', 'Green water', 'Kamu Kamu plaza'],
  ['Matooke', 'Pringles', 'Real Madrid FC', 'Laundry basket', 'Louvered vents'],
  [
    'Gipiri and Labong',
    'Nickelodeon',
    'Kilimall',
    'Standard chartered',
    'A Zipper'
  ],
  ['Dell computers', 'Groot', 'Alligators', 'River orange', 'Serena Hotel'],
  ['Bay watch', 'Watoto', 'American football', 'Kadongo kamu', 'Kitchen ware'],
  [
    'Boeng',
    'Studio apartment',
    'iryn namubiru namugongo',
    'The landlord',
    'Courts of law'
  ],
  [
    'The barbarians',
    'Kiira town council',
    'Gulu town',
    'Lugabile',
    'Toy Story'
  ],
  ['Sitya loss', 'Door mat', 'uganda museum', 'Gmail', 'Glazing'],
  [
    'The book of wisdom',
    'Sedimentary rocks',
    'Sky Lounge',
    'Porsche',
    'The Egyptians'
  ],
  [
    'Mirror Mirror on the wall',
    'Leap of faith',
    'The holy trinity',
    'Umeme',
    'Gipir and lobongo'
  ],
  ['Web browser', 'Life is good', 'Morgan Freeman', 'Rubber', 'The Lion King'],
  [
    'Civil Aviation Authority',
    'Ugandan Potholes',
    'Porous borders',
    'Transgender',
    'Salt bae'
  ],
  ['Patwa', 'Peer groups', 'Malcom X', 'Blood donor', 'A quest'],
  [
    'Yamaha',
    'Shower gel',
    'The human brain',
    'Gangnam Style',
    'Weighing scale'
  ],
  ['Flat roof', "That's life mwatu", 'Moses']
];
