import fs from "fs";
import csv from "fast-csv";
import * as R from "ramda";
import prettier from "prettier";

const result: any[] = [];
const stream = fs.createReadStream("./src/api/30-seconds.csv");

csv
  .parseStream(stream)
  .on("data", (data: any) => {
    result.push(data);
  })
  .on("error", console.error)
  .on("end", () => {
    const flat = flatten(result);
    const random = randomize(flat);
    const json = JSON.stringify(R.splitEvery(5, random));
    const content = prettier.format(
      `
          /* tslint:disable */ \n // this file is autogenerated \n
          export default ${json}`,
      { singleQuote: true }
    );
    fs.writeFile("./src/components/molecules/Pages/data.ts", content, err => {
      if (err) {
        console.error(err);
        return;
      }
      console.log("File has been created");
    });
  });

const flatten = (arr: string[][]): string[] =>
  R.uniq(R.flatten<string[][]>(arr).filter((word: string) => word && word.length));

const randomize = (arr: any[]) => {
  arr.forEach((_name: any, _index: any) => {
    const randomIndex = Math.floor(Math.random() * arr.length);
    const itemAtIndex = arr[randomIndex];
    arr[randomIndex] = arr[arr.length - 1];
    arr[arr.length - 1] = itemAtIndex;
  });
  return arr;
};
