/* tslint:disable */

// this file is autogenerated

export default [
  [
    'Uganda Chess Federation',
    'Dairy farming',
    'Autodesk',
    'Kifeesi',
    'Desire Luzinda'
  ],
  ['9 lives', 'Jinja Town', 'Kevin Hart', 'Kitugum', 'septic'],
  ['Kings of Leon', 'Kasubi tombs', 'Friday the 13th', 'Mobile money', '256'],
  ['Backtrack', 'Beside', 'Esau', 'Clark Kent', 'The Daily mornitor'],
  ['Coffee shop', 'Made in china', 'Nairobi', 'Gaeton Kagwa', 'Nike'],
  ['Shoprite', 'Cinderella', 'Wrist watch', 'Kawempe', 'Mun G'],
  [
    'Jessica Alba',
    'Kiwi',
    'Kowtow in your poohoo',
    "god's must be crazy",
    'Judith heard nalongo'
  ],
  [
    'Midcom',
    'North bridge',
    'An Intranet',
    'Uganda cancer institute',
    'Nice Biscuits'
  ],
  ['Looney Tunes', 'Line of symetry', 'Safe boda', 'Kikumi kikumi', 'KPC'],
  ['Mutaasa Kafeero Plaza', 'Special effects', 'Irene ntale', 'otada', 'SGS'],
  ['Piatto', 'Basoga', 'Picasso', 'Karamajong', 'Country music'],
  [
    'Winter is coming',
    '24k magic',
    'TVO',
    'Standard chartered',
    'Guvnor Night club'
  ],
  [
    'Grip gloves',
    'kakise',
    'The Department of justice',
    'Mitsubishi',
    'Autumn'
  ],
  ['Bell lager', 'Leonardo di Caprio', 'Kick boxing', 'Toy Story', 'Home run'],
  [
    'Andrew Mwenda',
    'UPDF Special Forces Command',
    'roof',
    'Barack Obama',
    'Lumia'
  ],
  [
    'Remote',
    'Mountain Gorilla',
    'Friday Night Lights',
    'Ham Towers',
    'Vitruvius'
  ],
  ['Anger management', 'Kira Motors', 'Glazing', 'King Oyo', 'Binding wire'],
  [
    'rafters',
    'Bujagali Falls',
    'Princes Diana',
    'Agnes Nandutu',
    'Milton Obote'
  ],
  [
    'Barkcloth',
    'Sphincter muscles',
    'Beauty and the Beast',
    'Presidential handshake',
    'Ne-yo'
  ],
  [
    'Stratosphere',
    'Nikon',
    'Bed bugs',
    'Rwabushenyi Memorial Chess Championship',
    'iryn namubiru namugongo'
  ],
  [
    'plan A',
    'Zambian President',
    'Every where you go',
    'Hajji Nasser ntege Ssebagala',
    'Acholi'
  ],
  ['Enteebe', 'Dexter', 'Nasser', 'Bad black', 'CHOGM'],
  ['Lights', 'metal plates', 'musisi', 'Rwanda', 'Bird flu'],
  ['Trevor Noah', 'Quencher', 'Bantu', 'Morogoro', 'Irene Namubiru'],
  [
    'Posho and beans',
    'Zinjanthropus',
    'Greenland Bank ',
    'apartments',
    'The Nile crocodile'
  ],
  ['Jack fruit', 'Nakawunde', 'Angry birds', ' Onyango Obbo', 'Ssanyu FM'],
  ['Bismilah', 'Jimmy Enabu', 'KFC', ' Meesi', 'Green star'],
  ['Kajjansi clays', 'Judaism', 'The Bistro', 'Ebee', 'Plot'],
  ['Mukwano', 'Alligators', 'Orient Bank', 'Kofi olomide', 'Dell computers'],
  [
    'land lord',
    'Benjamin Odoki',
    'Isis',
    'Life is good',
    'Central business district'
  ],
  [
    'Carriage way',
    'Gonja',
    'Shaulin soccer',
    'Kilembe Mines',
    'Iron bar thugs'
  ],
  ['Kadashians', 'Super dip', 'Insomnia', 'War Dogs', 'Yamaha'],
  ['UPC', 'Cisco', 'Posho', 'A walk in closet', 'Nido'],
  ['Lakwena', 'Sedimentary rocks', 'American dad', 'Salim Saleh', 'Java House'],
  ['Head lamps', 'plumbers', 'Liquid Silk', 'Adding machine', 'Drone'],
  ['Besigye', 'Fay', 'The Ebonies', 'Equity bank', 'Butabika'],
  ['Chapati', ' Okocha', 'Fizzy drinks', 'Agha Khan', 'FDC'],
  ['Samurai', 'Rig', 'Botanical gardens', 'Linkin park', 'Denzel'],
  [
    'Savero',
    'Chikomando',
    ' David Beckham',
    'Uganda Martyrs⁠⁠⁠⁠',
    'construction'
  ],
  [
    'The ministry of education',
    'The Ministry of Health',
    'Jomo Kenyatta',
    'Cheat codes',
    'The alpha'
  ],
  [
    'Parliament Avenue',
    'The blood moon',
    'Photoshop',
    'Acacia Mall',
    'Red Indians'
  ],
  ['Guard rail', 'Life Buoy', 'Linux', 'Mama Fiina', 'architects'],
  ['Prado', 'Lake Malawi', 'Jet ski', 'Kiwaani', 'Dubai'],
  [' Cheops', 'Facebook Messenger', 'Bamuda triangle', 'Ipsum', 'PCL'],
  [
    'Vj jingo',
    'The Geneva peace convention',
    'Friday nights live',
    'Rukidi IV of Toro',
    'Mt. Rwenzori'
  ],
  ['Boys 2 Men', ' Nefertiti', 'Crested Crane', 'Mean Machine', 'pregnant'],
  ['Motherboard', 'Royco', 'Wisdom tooth', 'Malwa', 'Kadongo Kamu'],
  ['Bullet proof vests', 'Dumpy level', 'To Expire', 'casting', 'conductor.'],
  ['Hipster', 'Jacob', 'Chameleone', 'Jackie chan', 'Lithium ion batteries'],
  ['Kenyatta', 'Honda', 'Tutankamun', 'Table mats', 'Bush Court'],
  ['Seychelles', 'Pascal', "Kabaka's Lake", 'The landlord', 'Halima'],
  [
    'The kyoola solar bus',
    'CECAFA 2010',
    'Luzira upper prison',
    'Cable carts',
    'Yusuf Lule'
  ],
  ['Stanley Ntagali', 'Bushera', 'Haka', 'Black Mamba', 'Mufere'],
  [
    'Texas Instruments',
    'Doom',
    'Tunisia',
    'Adam Sandler',
    ' Light and sound show'
  ],
  ['Mirror', 'Graphite', 'Express FC', 'Martin Luther King', 'Pepe Kale'],
  [
    'Owen Falls Dam',
    'The Ministry of Education and Sports',
    'Cameroonian',
    'The hostel',
    ' Music dance and drama'
  ],
  ['Amawulire', 'tanks', 'Pajero', 'Fatboy', 'Mt Kenya'],
  ['Rwenzori', 'Web browser', 'Wilson', 'Ubc', 'OO7'],
  ['Kabaka Mwanga', 'UTL Mango', 'State house', 'Ziggy Marley', 'Nickelodeon'],
  ['Anglican', 'Lake Victoria', 'Yaka', 'The omega', 'Muvule Tree'],
  ['Omo', 'A consul', 'Emperor Olando', 'Stone Town', 'Breakfast and bed'],
  ['Calculators', 'Nyama', 'Kololo', ' Goal line technology', 'Lake Kagera'],
  [
    'Pablo',
    'Mitsubishi',
    'Scaffold',
    'The good the bad the ugly',
    'Bbale Francis'
  ],
  [
    'Call of Duty',
    'Tea party',
    'Wbs',
    ' Kowtow in their poohoo',
    'Kazinga Channel'
  ],
  ['Australia', 'Airtel', 'Pingu', 'Lohnro Motors', 'Morgan Trainer'],
  ['Serena', ' Another rap', 'UEB', 'Cadbury', 'Power horse'],
  [
    'Bugolobi Flats',
    'Ivory Tower',
    'Washing machine',
    'The Pearl Guide Uganda',
    "King's College Budo"
  ],
  ['Adungu', 'Mary Mary', 'KK Security', 'Taste the feeling', 'Rwenzururu'],
  ['Nail polish', 'Supersport Blitz', 'Uzi', 'Kiwi', 'YMCA'],
  [
    'False prophets',
    'Margaret Thatcher',
    'Migingo Island',
    'Christians',
    'Kikomando'
  ],
  [
    ' Anslem',
    'Tip Top Bread',
    'Lugazi Sugar',
    'Nawab Asian Bistro',
    'Kato Lubwama'
  ],
  ['KCCA carnival', 'Catholicism', 'Dexters Lab', 'Scotch', 'Century Cinemax'],
  ['Lady Gaaga', 'Fala', 'Macintosh', 'ufo', 'Usher Reymond'],
  [
    'Super Dip',
    'The Gaddafi mosque',
    'Poker Face',
    'Lido Beach',
    'Jackie Chan'
  ],
  ['Sauti Sol', 'Lugogo Bypass', 'Bill Gates', 'Kosovo', 'Cleveland Cavaliers'],
  ['Kampala', 'Studio apartment', 'Akamba', 'Uganda House', 'South Sudan'],
  [
    'Volkswagen',
    'Kabale',
    'Coco sisters',
    'Uganda Management Institute',
    'Indian coolies'
  ],
  [
    'Dmark',
    'Phone booth',
    'Gipir and lobongo',
    'Victoria University',
    'Chameleon'
  ],
  ['Kwagalana group', 'Sekanolya', 'Buduuda', 'DP', 'Vacuum cleaner'],
  ['Lamy', 'Ludacris', 'Blu-ray disc', 'samsung', 'Professor x'],
  ['Hewlett-Packard', 'Colgate', 'Soulja Boy', 'Nandos', 'Blue 3'],
  ['Shau Khan', 'Sigiri', 'Wine', 'Chicken Tonight', 'Pancakes aka'],
  ['Juventus', 'Nissan Patrol', 'Café javas', 'Brood', 'Ntinda'],
  ['Dead shot', 'Nasser rd', 'Bobi wine', 'Bon Apetit', 'Paddle'],
  [
    'Jazz Supermarket',
    'Barcelona',
    'Kyambogo university',
    'Entebbe International Airport',
    'The Adventures of TinTin'
  ],
  [
    'We will not wait for karamoja to develop',
    'KPMG',
    'Omo',
    'Bad Brown',
    'Taxi conductors'
  ],
  [
    'Sadolin',
    'The East African',
    'Civil Aviation Authority',
    'Back hoe',
    'magnet'
  ],
  [
    'Jughead',
    '2001 Space Odyssey',
    'Mulago referral hospital',
    'Kabaka Mutebi',
    'The super bowl'
  ],
  ['Lady and the Tramp', 'Aladdin', 'The New Vision', 'Oryx', 'marie curie'],
  ['Awillo Longoma', 'New Zealand', 'Marco Polo', 'City Oil', 'Tito Lutwa'],
  ['Kiprotich', 'Java', 'Transistor', 'Gaz', 'River orange'],
  ['Scribes', 'Mt Kilimanjaro', 'Ankara', 'Silver Springs Hotel', 'Mallet'],
  ['LinkedIn', 'Bungee jumping', 'Reebok', 'Serena Hotel', 'Proton'],
  [
    'The School uniform',
    'Fela',
    'Chipoli',
    '1 Million',
    'Oxford Mathematical Set'
  ],
  ['Mosese Magago', 'Rubber', 'Standard chartered Bank', 'Postbus', 'wolverin'],
  [
    'Nakasongola',
    'Embooli',
    'Casablanca',
    'King Fahd Plaza',
    'Magnetic flux density'
  ],
  ['Spock', 'KIA', 'Lake katwe', 'Ekitaguriro dance', 'Maradona'],
  ['Godzilla', 'Namilyango College', 'Bogoya', 'Poko poko', 'family guy'],
  ['9th October', 'Ubuntu', 'Mediterranean Sea', 'DFCU', 'Hotel Africans'],
  ['FUBA', 'UNRWA', ' Ronaldo', 'Kanye West', 'Sudhir Ruparelia'],
  ['kalita', 'Kasoli', 'Katwe', 'Patrick Mbire', 'Kamu Kamu plaza'],
  [
    'Quencher',
    'Mahatma ghandi',
    'Tommy Hilfiger',
    'Concentrate admixtures',
    'Watoto Church'
  ],
  [
    'Sodium',
    'Pioneer mall',
    'Theatre la Bonita',
    'Kansanga Miracle Centre',
    'Owl city'
  ],
  [
    'Mukwano cooking oil',
    'Energizer',
    'Pope John Paul the 2nd',
    "Chameleon's tongue",
    'Eminem'
  ],
  ['Riham biscuits', 'Macos', 'The leopard', 'Mukene', 'The Kyabaziga'],
  ['Molokony', 'Fly540', 'Afcon', 'State minister', 'Lama'],
  ['Loubega', 'Cartoons', 'Bwaise', 'Coffee spirit', 'Hannah Montana'],
  ['Spalding', 'Kaloodo', 'Saala Puleesa', 'Kigali', 'Miley Cyrus'],
  [
    'Checkers',
    'Denis Obua',
    'Irene brake',
    'Shimoni Primary Shool',
    'Mine Boy'
  ],
  ['Kings of Leon', 'Lukaya', 'Heathens', 'Olympus has fallen', 'Chuck Bass'],
  [
    "Air Jordan's",
    'The pyramids',
    'Uganda airlines',
    'Kiss of death',
    'Chuck Noris'
  ],
  ['Uhuru', 'Maputo', 'Good year', 'Kale Kayihura', 'Beetleborgs'],
  ['Mercedes SLR', ' Cleopatra', 'Noor', 'Sheraton', 'Alex Ndawula'],
  ['The Kampala casino', 'City square', 'Paul kafeero', 'Umeme', 'Bebe Cool'],
  [
    'Kampala Cocktail Week',
    'Tsetsefly',
    'Pope Francis',
    'Uganda Telecom',
    'Tip Top Bread'
  ],
  [
    'Internet cafe',
    'Y2K',
    'The omuzinga',
    'face technology',
    'Kings college Budo'
  ],
  ['JFK', 'Barclays', 'The friend zone', 'Samosas', 'Madagascar'],
  ['Kalangala', 'Henry Newton', 'HP', 'magma', 'Street art'],
  ['Snake', 'Easter Monday', 'Sheebah Kalungi', 'Steve Jobs', 'Shakes Fimbo'],
  [
    'Margaret Trowel school of fine art.',
    'Garlic stew',
    'Nakasero market',
    'The ugandan air force',
    'Ford'
  ],
  ['Allan Kasuja', 'Patwa', 'Bugolobi', 'Sportsbet', 'Shaggy'],
  [
    'Queen Latifa',
    'Kiira town council',
    'Fotogenix',
    'Masaka road',
    'Ekyimbeewo'
  ],
  [
    'Uganda Silverbacks',
    'West Nile tribe',
    'Portbell',
    'Spearmint',
    'Malcom X'
  ],
  [
    'Water purification',
    'Ketchup',
    'Cheese bread',
    'The lion king',
    'Mohamad Ali'
  ],
  ['Mirinda fruity', 'Sekitulege', 'Kigali', 'Sheebah', 'Samurai x'],
  ['Tony stark', 'Peter and Jane', 'Ange noir', 'Saint', 'Marvin Gaye'],
  [
    'Katumba wamala',
    'Sugar mommies',
    'Internet',
    'Uganda Broadcasting Corporation',
    'Bendicto Kiwanuka'
  ],
  ['Fraud', 'Firebase', 'Bungee jumping', 'NBS', 'Edward Mutesa'],
  ['Olanya Colombus', 'Suits', 'Luzira', 'Animaniacs', 'Mouse traps'],
  [
    'Work work work work',
    'zari',
    'Typhoid',
    'Uganda Airways',
    'Robert Kiyosaki'
  ],
  ['Viber', 'Humps ahead', 'Bujagali falls', 'Hewlett Packard', 'Pimp'],
  ['Buganda', 'Jehover witness', 'Alteeza', 'Gen Katumba Wamala', 'Africell'],
  ['iTunes', 'African crafts', 'Murchison falls', 'KFM', 'AIDS'],
  ['Land of milk and honey', 'Kodak', 'Mwenge bigere', 'Power FM', 'HIV'],
  [
    "That's life mwatu",
    'Adolf Hitler',
    'Total',
    "The Assassin's creed",
    'Mosquitoe'
  ],
  [
    'Bat valley theatre',
    'Case clinic',
    'Shell',
    'Red Pepper',
    'The Ssese islands'
  ],
  ['Samuel L. Jackson', 'AON', 'The exodus', 'Game zone', 'Friendship taxi'],
  ['Spectrum', 'Abraham', 'Speke resort munyonyo', 'Obote', 'Panamera'],
  ["G4s McDonald's", 'Pete Sampras', 'Instagram', 'Simba Telecom', 'Kasangati'],
  [
    'Al Shabbab',
    'Forex exchange',
    'E! Entertainment',
    'Janan Luwumu',
    'Omweso'
  ],
  ['Navigator', 'Bic', 'Marie Antoinette', 'Isaac Newton', 'Fitness trackers'],
  [
    'The Source of the River Nile',
    'Kiira EV',
    'Black sheep affair',
    'SC Villa',
    'Kira motors'
  ],
  ['Huawei', 'Toyota', 'The X factor', 'Canon', 'Lake kyoga'],
  [
    'Flamingo',
    'Kampala golf course',
    'Pick n Peel',
    'Kyadondo Rugby Club',
    'Pemba Warriors'
  ],
  ['Game of thrones', 'Copper rods', 'Snowwhite', 'The Beatles', 'Phanero'],
  ['Kintu', 'Xfm', 'Ray Charles', 'Jik', 'Godfrey Massa'],
  [
    'Beyoncé',
    'Real Madrid FC',
    'The us navy seals',
    'Fly on your own',
    'Swimming pool'
  ],
  ['Mark Zuckerberg', 'Dfcu bank', 'Suicide squad', 'Mabira forest', 'Kanungu'],
  ['Hashtag Rap', 'Moreen kyalya', 'Kakande', 'Picfare', 'Kibwetere'],
  ['Valentine', 'Kitoko', 'Lcd', 'Chocolate syrup', 'Eddie Kenzo'],
  [
    'The dictator',
    'The national theatre',
    'R. Kelly',
    'Lord of the rings',
    'Rwandair'
  ],
  [
    'Planet of the apes',
    'Mulago hospital',
    'Bukoto Flats',
    'Goodnight',
    'Othello'
  ],
  ['Teso', 'Maso awo ', 'Condom', 'A Chariot', 'Charles Darwin'],
  ['Woolworth', 'Kisoro district', 'Village Mall', 'MTV', 'The Dukka'],
  ['Uganda railway', 'Nail clippers', "Worker's House", 'Dubai', 'SMACK'],
  [
    'Rav4',
    'Interior designers',
    "Communication's House",
    'Ear plugs',
    'Invisible children'
  ],
  [
    'Mapeera house',
    'Robert Downey junior',
    'Capital Shoppers promotion',
    'Jeniffer Musisi',
    'Miya farouk'
  ],
  ['Beautiful mess', 'Gameboy color', 'Bald', 'Seya ', 'Semliki National Park'],
  ['Gmail', 'Boeng', 'engineers', 'Air Uganda', 'Syschelles islands'],
  [
    'Music system',
    'Kampala International University',
    'Rwenzori Mountains',
    'slabs',
    'Nawab Asian Bistro'
  ],
  [
    'East African development bank',
    'Uganda Revenue Authority',
    'Mountain Elgon',
    'Bbale Francis',
    'Ronald Reagan'
  ],
  ['Bull', 'The Niagara falls', 'Vienna College', 'Lexus', 'Cool cool bar'],
  [
    'Swangz Avenue',
    'Mabirizi Complex',
    'The accountant',
    'Manchester united',
    'Iceland'
  ],
  [
    'city parents',
    'Middle East consultants',
    'Weetabix',
    'Morgan Freeman',
    'Boxing gloves'
  ],
  ['Weed', 'James bond', 'Idi Amin Dada', 'Theodolite', 'Pintrest'],
  ['The North Star', 'Pool Court', 'Oxygen', 'UPE', 'residence'],
  [
    'Mark x',
    'Club silk',
    'Louvered vents',
    'Edward Kale Kayihura',
    'Alien ware'
  ],
  ['xmen', 'Auto correct', 'Mechanised systems', 'Kiboko', 'Property agents'],
  ['Forex Bureau', 'Cool cool bar', 'Lady Gaga', 'Mamdani', 'Whore'],
  ['Jacuzzi', 'Margarine', 'PLE', 'Polygamy', 'Acer'],
  [
    'Floor traps',
    'Terms and conditions',
    'Age of empires',
    'Cheer leaders',
    'FUFA'
  ],
  ['Garden Tea', 'Paul Walker', 'Doctor', 'CCCC', 'KIU'],
  [
    'Timber',
    'Sama-saulting chicken',
    'Game nights',
    'Mweya safari lodge',
    'Insurance broker'
  ],
  [
    'Wandegeya chicken',
    'Tamarai',
    'Queen Elizabeth',
    'Public holiday',
    'TV chicken'
  ],
  [
    'Janet Kataha Museveni',
    'Kidepo national park',
    'Pillows',
    'Milk',
    'Power puff girls'
  ],
  [
    'Napoleon Bonaparte',
    'Pablo Escobar',
    'Jesa',
    'Express FC',
    'Makerere university'
  ],
  ['Sharpie', 'Bukedde', 'Forest Mall', 'VGA', 'Angelina Jolie'],
  [
    'Caterpillar',
    'Lugogo Mall',
    'Uganda cranes',
    'Sodium carbonate',
    'Quality chemicals ltd'
  ],
  ['Jose Morinho', 'iPhone 7', 'fabrication', 'Phablet', 'Bean weavals'],
  [
    'Micho ',
    'Kabira country club',
    "Art's students",
    'Quality Supermarket',
    'Doris Akol'
  ],
  ['Paintball', 'Carpool', 'Crane bank', 'Plastic smiles', 'Dunlop'],
  ['Cardboard', 'Air guitar', 'plaster', 'Cold play', 'Shoe'],
  [
    'Time traveller',
    'Mumbere',
    'Cherokee',
    'Kenya Airways',
    "Saint Mary's Kisubi"
  ],
  [
    'mulindwa lawrence',
    'Golola Moses',
    'Hypocritical analysis',
    'Fake hair',
    'mukiibi lawrence'
  ],
  ['Wizkid', 'Vernier caliper', 'This side up', 'Katanga', 'The Alchemist'],
  ['Karuma', 'Michael Jackson', 'Mr. Kampala', 'Delident', 'Celtel'],
  ['Cassava', 'University professor', 'Daddies', 'Psquare', 'William Obote'],
  [
    'Cineplex',
    'ABBA',
    'Quality over quantity',
    'Godrey Binaisa',
    'Mohamad Nseroko'
  ],
  ['Debanj', 'Night prep', 'TASO', 'Sugar daddies', 'Wolokoso'],
  ['Sleeping sickening', 'Nandujja', 'kakalambada', 'Lubiri', 'Ebola'],
  [
    'The Democratic Republic of Congo',
    'Wakaliwood',
    'We Young Women and Men of Uganda',
    'Steven Kavuma',
    'Burundi'
  ],
  ['Fort Jesus', 'Gipiri and Labong', 'Cassette tape', 'ISU', 'Gap year'],
  [
    'All Saints Cathedral',
    'Telefunken',
    'Monalisa',
    'Buganda Road Primary School',
    'Endongo'
  ],
  ['Lagos Naija', 'The Serengeti', 'uganda museum', 'Uber', 'Weetabix'],
  ['Obey your thirst', 'Aristoc', 'ISIS', 'Vienna', 'Chris Adams'],
  [
    'Oliver Twist',
    'Namboole Stadium',
    'Hot loaf',
    'Porous borders',
    'Austraia'
  ],
  ['Kalo', 'Ghetto President', 'Sir Alex Ferguson', 'Shower gel', 'Mohhock'],
  ['Pringles', 'Fantastic Four', 'Mubs', 'Eagles band', 'NTV'],
  ['Hair dye', 'Monopoly', 'Ugandan girls', 'The Big Five', 'GoTv'],
  ['Mt. Elgon', 'Dar-es-salaam', 'Scrabble', 'UB40', 'Albert Einstein'],
  [
    'Colour schemes',
    'NASA',
    'Julius Nyerere International Airport',
    'The davinci code',
    'Polo'
  ],
  ['Kalooli', 'Passengers', 'Woodball', 'Oasis mall', 'The book of wisdom'],
  ['Toyota Vitz', 'Bob Marley', 'Mutation', 'The avengers', 'Erias lukwago'],
  [
    'The secret life of bees',
    'Rugby',
    'Tullow Oil',
    'Goloola Moses',
    'Terminator'
  ],
  [
    'Long horned cattle',
    'Channel O',
    'Solex padlock',
    'Kampala International School Uganda',
    'Double A batteries'
  ],
  [
    'Fiji',
    'Rainbow International School',
    'Sweat glands',
    'Grand theft auto',
    'Game'
  ],
  [
    'Education',
    'Ice age',
    'Bukedde TV',
    'Cumulative frequency',
    'Solar Eclipse'
  ],
  [
    'Muwogola dance',
    'John 3:16',
    ' General Biraro',
    'Kericho Tea',
    'Swissgarde'
  ],
  [
    'Sega Mega Drive',
    'Nankasa dance',
    'Christian Bale',
    'Carbon copy',
    'Jumia'
  ],
  [
    'Uganda Telecome',
    'Rwot Kweri',
    'Nalufuka dance',
    'Gordon Wavamuno',
    'Detol'
  ],
  ['Aristoc', 'Four cousins', 'Iris', 'Mwanga dance', 'Stella Nyanzi'],
  [
    'Kampala Parents school',
    'Malaba',
    'Uganda clays',
    'NFL',
    'Runyege and Entongoro dance'
  ],
  ['Kizza Besigye', 'Cannabis', 'Adungu dance', 'Jacob Oulanyah', 'Blu 3'],
  ['Nile Special', 'Nana hostel', 'Bruce Willis', 'Arusha', 'Reaching heights'],
  [
    'Klashvinkov',
    'Mission Impossible',
    'NBA 2016',
    'Wembley stadium',
    'Ennanga'
  ],
  ['Source of the nile', 'Milkman', 'Wall clock', 'Boxers', 'Telephone'],
  ['Clock tower', 'Sony vaio', 'Mouse trap', 'Engalabi', 'Queen of katwe'],
  [
    'Battery Low',
    'Lake Bunyonyi',
    'System unit',
    'Oil And petroleum',
    'Endere'
  ],
  ['Cairo international bank', 'Moi', 'Enkwanzi', 'Hewlett Packard', 'Youtube'],
  ['Morgue', 'The Daily Monitor', 'Shaka Zulu', 'Amakondeere', 'Mosquitoes'],
  [
    'Justin Beiber',
    'Diarrhoea',
    'ABSA premier league',
    'Moses',
    'Uganda National Bureau of Standards'
  ],
  [
    'Lagos',
    'Gnl',
    'Luwombo',
    'Kitchen ware',
    '[22:13, 2/27/2017] +256 702 204609: Logitech'
  ],
  ['Mozart Wolfgang', 'Gadafi', 'Santa', 'Isuzu', 'Spa'],
  ['Polar bears', 'Tesla', 'CBS', 'Kyadondo rugby grounds', 'Chapatti'],
  ['Makerere', 'Jinja', 'Mandazi', 'Jada Pinket', 'Pelican'],
  ['Maurice Kirya', 'A Locket', 'Water slide', 'Purple Rain', 'A wordrobe'],
  ['pipes', 'Hipsters', 'Ok Google', 'Service duct', 'A company profile'],
  ['MySpace', 'Gold', 'Pombe', 'Solar cell', 'Diamonds'],
  ['Mr Bean', 'Zumba', 'Habari', 'Kane and Abel', 'Nokia'],
  ['Kobs', 'Snowden', 'Gattomato', 'Midcom', 'Silk Royale'],
  ['Night soil', 'Internet explorer', 'The notebook', 'Cool cool bar', 'Groot'],
  [
    'Club Play',
    '50 First Dates',
    'Ben Kiwanuka',
    'The grasshopper month',
    'Mt muhavura'
  ],
  ['Mauritania', 'Monot', ' Kaihura nkuba', 'Cake', 'Unilever'],
  ['Ugly Betty', 'John Magufuli', 'Sky Lounge', 'Samsung galaxy', 'Forest'],
  ['Club Amnesia', '1000 ways to die', 'The hub', 'Happy hour', 'ITunes'],
  [
    'Queen bee',
    'Nokia tune',
    'Rotten Tomatoes',
    'Vladimir Putin',
    'Nile Perch'
  ],
  ['Puss in boots', 'Clouds', 'KIU Titans', 'Pompeii grill', 'Corolla'],
  ['Joseph Mabirizi', 'Lake Albert', 'GPS', 'Simba FC', 'Tusker project fame'],
  ['UNEB', 'Rice porridge', 'Soweto', 'Betty kamya', 'Coffee mug'],
  [
    'Aliko Dangote',
    'Angels and Demons',
    'Betway Kobs',
    'Arsenal FC',
    'Will Smith'
  ],
  ['Hima Cement Heathens', 'plan B', 'Guvnor', 'KLM', 'Musaawo'],
  ['Mozilla', 'Karamoja', 'The embassy', 'Bella Wine', 'Malaria'],
  [
    'Grip gloves',
    'Sprint',
    'Stephen Omony',
    'Multichoice',
    'Samsung galaxy note 4'
  ],
  [
    'Brian Odong',
    'Land Cruiser',
    'Ice ice baby',
    'Second Chance',
    'Micheal Jackson'
  ],
  [
    'Noddles',
    'Last king of Scotland',
    'Aerial',
    'Tororo Rock',
    'The Pearl of Africa'
  ],
  ['Diskette', 'Piato', 'Wallstreet', 'Windows 3.1', 'Namboole'],
  [
    'Fastjet',
    'Ms DOS',
    'Neon',
    'Kintu and Nambi',
    'Indiana Jones and the Last Crusade'
  ],
  [
    'Casio',
    'Lugogo Cricket Oval',
    'Bruce Lee',
    'Ninja worrier',
    'Evander Holifield'
  ],
  [
    'Macarena',
    'Stone Cold Steve Austin',
    'Full beam lights',
    'Navio',
    'Mwana-mujimu'
  ],
  [
    'The Mighty Morphin Power Rangers',
    'Jetlee',
    'Door stoppers',
    'Usain bolt',
    'Renault'
  ],
  ['Red Bull', 'Ak-47', 'Bible house', 'Ihk', 'Woolworths'],
  ['The Etihad', 'Apeta', 'Badru Kigundu', 'Ludo', 'Chicoco'],
  ['Mozambique', 'Mufasa', 'Sound of music', 'Bill Gates', 'Blind spot'],
  [
    'NRM',
    'Radio and Weasel',
    'The arsenal massacre',
    'Habari , kabi , danger',
    'Whatsapp'
  ],
  ['Liquid soap', 'Maths', "St mary's Kitende", 'Coach Carter', 'Raila Odinga'],
  [
    'Jim Muhwezi',
    'Wireless Fidelity',
    'Alshabaab',
    'Specioza Kazibwe',
    'The 9th of October'
  ],
  [
    'Gorillos',
    'Emmanuel Tumusime Mutebile',
    'How I met your mother',
    'Simplex network',
    'Zuena'
  ],
  [
    'Fresh diary',
    'Bruno Mars',
    'National Water and Sewerage Corporation',
    'interior design',
    'Subaru'
  ],
  [
    'Yoweri Kaguta Museveni',
    'Need for speed',
    'Jinja road',
    'Monica Lowinsky',
    'soak pit'
  ],
  ['WWE', 'Who killed captain Alex', 'Sugar cubes', 'KCCA FC', 'Naguru'],
  ['Sese gateway Beach', 'Hima cement', 'Splash', 'Tyson Waragi', 'Beans'],
  ['MTN', 'Christmas', 'White ants', 'Nakasero', 'Steven Spielberg'],
  ['January', 'Lake View Hotel', 'The rich also cry', 'Bake', '350 mls'],
  [
    'Salvador',
    'Kitante Primary School',
    'Kampala Carnival',
    'Bhagdad',
    'Pay as you earn'
  ],
  [
    'Kampala Restaurant Week',
    'Gangnam Style',
    'Boda boda',
    'Roofings',
    'Dr. Bosa'
  ],
  [
    'Christian fellowships',
    'Wink',
    'Kobil',
    'Zara',
    'Uganda Manufacturers Association'
  ],
  ['Bay watch', 'Northern bypass', 'PPDA', 'Mulwana empire', 'Handle'],
  ['The ten commandments', 'Reggae music', 'Sansa', 'Agataliko Nfuufu', 'Core'],
  ['Uhuru Kenyatta', '300', 'Louvres', 'Daniel Arap Moi', 'Poker'],
  ['American pie', 'Back hoe', 'The Joker', 'Umoja', 'Kabaka Mwenda Mutebi II'],
  ['Agwara', 'Popcorn', 'Precision Air', 'Canoes', 'Sponge Bob'],
  [
    'Lake Tanganyika',
    'Janet Museveni',
    'Methane gas',
    'Sony Ericsson',
    'Phillips'
  ],
  ['Bata', 'Siri', 'Rwakitura', 'Tropical Heat', 'Tamale mirundi'],
  ['Katogo', "5 1/2' floppy disc", 'Iyingo', 'Gym', 'Guitar'],
  ['Robert Mugabe', 'Black Swan', 'Buglar proofing', 'Sticky keys', 'Cairo'],
  ['Namugunga', 'Zero grazing', 'Toyota Corolla', 'Abuja', 'The Nile'],
  ['Baakisiima dance', 'The Sun', 'Etofali', 'Allen Kagina', 'Accra'],
  ['Fila', 'Tunis', 'Ggaba beach', 'Nakumatt', 'Tuskys'],
  [
    'Beast Wars',
    'Mega Standard Supermarket',
    'The Hulk',
    'Sitya loss',
    'Israel'
  ],
  ['CPU', 'Gators Cafe', 'Hey there Delilah', 'Greenland', "The LRA's Kony"],
  [
    'Sadolin paints',
    'Nokia katochi',
    'The holy trinity',
    'Uganda Coffee Development Authority',
    'Night dancers'
  ],
  [
    'Pope John Paul II',
    'Ferry',
    'Nice clear',
    'London has fallen',
    'Ugly Duckling'
  ],
  ['Air force one', 'New taxi park', 'DHL', 'A submarine', 'The Simpsons'],
  [
    'Apple',
    'Avocado',
    'The London eye',
    'Masaka-mbra highway',
    'White water rafting'
  ],
  ['Mount Kadam', 'Ludo', 'Pit latrine', 'Tecno', 'The Kayola bus'],
  [
    'Subaru Imprezza',
    'Wine opener',
    '[22:55, 2/27/2017] +256 773 106724: Community policing',
    'Mpenkoni',
    'Anne Kansime'
  ],
  [
    'Landrovers',
    'Moses Ndiema Kipsiro',
    'Highland mineral water',
    'Animal farm',
    'Sweet Pepsi'
  ],
  ['Karate Kid', 'Auckland', 'Caster Semenya', 'An Apache', 'Ekizino dance'],
  [
    'Ugali',
    'Jacob Zuma',
    'Mountain Moroto',
    'Constantine',
    'The French Revolution'
  ],
  [
    'Adobe master collective suite',
    'Hit man',
    'World Wrestling Federation',
    'Greenlands Bank',
    'Arusha'
  ],
  [
    'Teletubbies',
    'Arabica coffee',
    'Atom',
    'Amabere ya Nyinamwiru',
    'Fanta Fruit Blast'
  ],
  ['Gaetano kagwa', 'Mnet', 'Everywhere you go', 'Alter wine', 'One by one'],
  ['Poker face', 'Kololo airstrip', 'The acacia place', 'atin paco', 'Sudhir'],
  [
    'Silicon chips',
    'Paint specifier',
    'Rock Paper Scissors',
    'Aristoc',
    'Tigerhead'
  ],
  [
    'Star Wars',
    ' Game night is fun',
    'Old taxi park',
    'Ktv',
    'Entebbe International Airport'
  ],
  ['Phillips', 'Spellings', 'Kawunyemu', 'Spelling bee', 'Akadinda'],
  ['Zoom Club', 'Snapchat', 'Luke Skywalker', 'Mccauley Culkin', 'Arse'],
  [
    'Stucco paint',
    'The championchampions league',
    'LinkedIn',
    'City Oilers',
    'concrete'
  ],
  ['Sangoma', 'Steve Jobs', 'Ofwono', 'Olx Uganda', 'Amazon Kindle'],
  ['manhole', 'Shrek', 'In heavens no beer', 'Street Fighter', 'Porsche'],
  [
    'Sonic the Hedgehog',
    'Uganda national anthem',
    'Mr IBU',
    'Rwenzori Mineral Water',
    'Ngongoro Crater'
  ],
  ['Binding tape', 'Bugs Bunny', 'Hi vis vest', 'Daffy Duck', 'Munyonyo'],
  [
    'Yosemite Sam',
    'Nakasero Primary School',
    'Smart wire',
    'Bunsen burner',
    'Pokemon'
  ],
  ['Lugabile', 'Digimon', 'Extension cable', 'Red Carpet', 'Landline'],
  ['Microsoft', 'Africa', 'Owino market', 'The green light', 'Paul Kagame'],
  [
    'Maggie Kigongo',
    'The smartphone network',
    'Land mines',
    'Muzikiti',
    'Vintage cars'
  ],
  [
    'Chair cushions',
    'The goatee',
    'Jackie Chandiru',
    'Nvidia graphics card',
    'The synagogue church'
  ],
  ['Kafuunda', 'Emirates stadium', 'Speke apartments', 'Pirelli', 'Nike frees'],
  [
    'Wanale',
    'A quality surveyor',
    'Fanta Fruity',
    'Protestant',
    'Kakira Sugar'
  ],
  ['Dead party', 'The Lion King', 'Green water', 'Mambo number 5', 'Walumbe'],
  ['The Globe', 'Pedlum Bob', 'Donkey Kong', 'Google', 'Fifa 2016'],
  [
    'Noise proof',
    'Justice league',
    'Chlorine gas',
    'Easter Monday',
    'Merry-go-round'
  ],
  [
    'Camouflage',
    'Cheese',
    'Linen cloth',
    'The Royal Guards',
    'Big Brother Africa'
  ],
  [
    'Irongo dance',
    'Mandazi',
    'Rolex',
    'Joe Bidden',
    'Teenage Mutant Ninja Turtles'
  ],
  ['La Pattisserie', 'Kony', 'Wanchekecha', 'Micro SD card', 'Invaka Trump'],
  ['Stanbic Bank', 'Garden city', 'BomberMan', 'Cumlo-nimbus clouds', 'Mehta'],
  ['Neyo', 'Ewe', 'Brittania', 'Uganda Waragi', 'December'],
  ['Barber Shop', 'Duracell', 'Kitengi', 'Telegram', 'Phantom zone'],
  [
    'Punch cards',
    'Netflix',
    'Plot number and block number',
    'Nice house of plastics',
    'Spiderman'
  ],
  [
    'Davis and Shirtliff',
    'Kati Kati',
    'Sebagala and Sons',
    'Chinue Achebe',
    'Morgan Feeman'
  ],
  [
    "Valentine's day",
    'Sega Dreamcast',
    'Certificate of appreciation',
    'Baseball',
    'Horse shoe'
  ],
  [
    'Ruhakana Rugunda',
    'The East African Community',
    'Bay watch',
    'Uganda National Roads Authority',
    'Kampala Carnival'
  ],
  ['Hwansung furniture', 'Smigo', 'Saudi Arabia', 'Renault', 'Bell Lager'],
  ['4G', 'Kimberly mines', 'Mediterraneo Restaurant', 'cityoil', 'Shakira'],
  ['Big size', 'Lamp post', "Don't be like bro", 'Mirinda', 'Kangaroo jack'],
  [
    'Caffesserie',
    'Daudi Ochieng',
    'Burkina Faso',
    'A Wish list',
    'The Black Mambas'
  ],
  [
    'URA FC',
    'Ggaba beach',
    'Reset button',
    'Dunhill',
    '[16:05, 2/27/2017] +256 702 204609: 9th October 1966'
  ],
  [
    'Crime preventers',
    'Eiffel tower',
    'Superman v Batman',
    'Matooke',
    'The Dark Knight'
  ],
  [
    'Ssebagala and sons electrical supplies',
    "As thin as radio's arms",
    'Zone 7',
    'Peer groups',
    'Sony Walkman'
  ],
  [
    'Ofwono bottle',
    'The Ministry of Foreign Affairs',
    ' The great Pyramids of Giza',
    'The Ministry of Finance',
    'Gulu town'
  ],
  ['Flat roof', 'Capital FM', 'Muzungu', 'Leverage', 'Captain Planet'],
  ['Sanyu FM', 'Ykee Benda', 'Chinese', 'Nze Nimiro', 'ABSA'],
  [
    'Muna Kampala',
    'Chelsea FC',
    'Nakasero blood bank',
    'The hobit',
    'Centenary Bank'
  ],
  ['Shaggy', 'The Republic of Kenya', 'Boda', 'Sunset beach', 'Winterland'],
  ['Chicken brain', 'Iron ore', 'Golf', 'Virtual reality gear', 'Mississippi'],
  [
    'Wavah water',
    'Winter',
    'Animal hides',
    'Wine cork',
    'The Haunted Hathaways'
  ],
  [
    'naalya',
    'American football',
    'Double glazed glass',
    'Cortana',
    'Transcend'
  ],
  [
    'Etihad stadium',
    'Timothy',
    'Afrobasket Championships',
    'Chief begger',
    'Generations'
  ],
  [
    'Broke',
    'Leceister FC',
    'Crazy Cock',
    "Okot p'Bitek",
    'Namirembe Cathedral'
  ],
  [
    'Robbin island',
    'Siri',
    'Golden State Warriors',
    'Snow white and the seven dwarfs',
    'foremen'
  ],
  [
    'A blogger',
    'Stephen Curry',
    'Clay pots',
    'Lebron James',
    'Sitting at the high table'
  ],
  ['Nancy Drew', 'The QWERTY', 'And1', 'Dell optiplex', 'Marabu stork'],
  [
    'Aronda nyakairema',
    'African Cup of Nations',
    'HTC phones',
    'Winnie Nwagi',
    'Pittsburgh steelers'
  ],
  ['Dorcus Inzikuru', 'Door knob', 'A quest', 'Ethiopian Airways', 'Premio'],
  [
    'Ultrasound machine',
    'Bakayimbira Drumactors',
    'UV rays',
    'Arsene Wenger',
    'John speke'
  ],
  ['Anita Fabiola', 'The River Nile', 'EPL', 'South Sudan', 'EAC'],
  ['Spacio', 'Roke Telekom', 'Vuzu Tv', 'Spur', 'Butcherman'],
  ['TATA', 'Glazing', 'Rick dees and americas top 40', 'SADC', 'Tripod stand'],
  ['COMESA', 'Dictionary', 'Leica', 'German shepherd', 'Otafire'],
  ['Everready', 'BBC', 'Star fish', 'CNN', 'Borosilicate'],
  ['Hallmark', 'Shisha', 'Nursing', 'Akamwesi hostel', 'Asus'],
  ['Kawunda suit', 'Kamyu', 'A flight simulator', 'Oseke', 'Traffic jam'],
  ['Muhammad Ali', 'PTSD', 'Bedbug', 'columns', 'Ssese Islands'],
  ['Kyanja', 'Juba', 'Bank robbers', 'Bwola dance', 'The Mexico-usa border'],
  [
    '2016 Presidential elections',
    'Human trafficking',
    'Beams',
    'Early man',
    'Patrick idringi'
  ],
  ['Kobe Bryant', 'Dasani', "Dr. Shaque O'Neal", 'Mars', 'The undertaker'],
  [
    'Chips and chaps',
    'MoneyGram',
    'Diarrhoea',
    'Highland water',
    'Stick bread'
  ],
  ['Wheat grains', 'Delta air', 'Dodo', '1900 Buganda Agreement', 'Giggles'],
  ['Omo', 'Lenovo', 'Fa', 'Red', 'Geisha'],
  [
    'Vulnerable persons',
    'Nokia 3310',
    'Napoleon Bonaparte I',
    'Vim',
    'Gaddafi'
  ],
  ['Big G', 'Flu shots', 'Owen falls dam', 'Flea', 'PK'],
  ['Go cart racing', 'Matatu', 'Betty Nambozi', 'Reptiles', 'Lilian Mbabazi'],
  ['Rock Boom', 'John Akii-Bua', 'King Kong', 'Kurosaki ichigo', 'Mengo'],
  [
    'Guard rail',
    'The world atlas',
    'Teenage Mutant Ninja Turtles',
    "That's Life Mwatu",
    'Italia'
  ],
  ['Home Alone', 'Club Ambiance', 'Wandegeya', 'Balokole', 'Wedding Meeting'],
  [
    'Ducati',
    'Janet Jackson',
    'George of the Jungle',
    'The Jackson Five',
    'Startimes'
  ],
  [
    'Earth, Wind and Fire',
    'Mirror Mirror on the wall',
    'St. Augustin',
    'KIA',
    'AC Milan'
  ],
  ['Tv Africa', 'The observer', 'Kalo', 'Inter Milan', 'SI unit'],
  [
    'Fragrance',
    'Barcelona FC',
    'Endingidi',
    ' Cristiano Ronaldo',
    'To engrave and embroid'
  ],
  [
    'Lex Luther',
    'Nintendo 64',
    'The mummy returns',
    'Lady Cranes',
    'The adventures of Tom Sawyer'
  ],
  [
    'Sony Playstation',
    'Video Library',
    'Microsoft Xbox',
    'BETWAY',
    'things fall apart'
  ],
  ['Semei Kakungulu', 'Jukebox', 'Snakes and ladders', 'M23 rebels', 'Jarvis'],
  ['Jean Claude Van Damme', 'Bed wetters', 'Chuck Norris', 'Iss', 'Kansanga'],
  ['NBA', 'Kabalagala', 'Curfew', 'Rush Hour', 'The big bang'],
  [
    'East African Reggae Bashment Crew',
    'Science students',
    'Garden Tea',
    'Value added tax',
    'The Easter bunny'
  ],
  [
    'Daily Monitor',
    'The Republic of Tanzania',
    'Mamba',
    'The maple leaf',
    'Browser history'
  ],
  [
    'The barbarians',
    'Magufuli',
    'Kazire',
    'Civil aviation authority',
    'Intern doctors'
  ],
  [
    'Southampton.',
    'Kendrick Lamar',
    'Zanzibar',
    'Previously on',
    'The prison break'
  ],
  [
    'Designated survivor',
    'The nervous system',
    'Kilimall',
    'Salivary glands',
    'Larakaraka'
  ],
  ['geoffrey massa', 'Emirates', 'Facebook', 'Uhuru kenyatta', 'A burger meal'],
  [
    'Burger King',
    'The Swiss alps',
    'Apple pie',
    'Juliana Kanyomozi',
    'Haris international'
  ],
  ['Poker face', 'Big O', 'Capital Shoppers', 'U-turn', 'Shopping voucher'],
  [
    'Song of Lawino',
    'Honey moon',
    'Low battery',
    'Scratch proof',
    'Water proof'
  ],
  [
    'The voice',
    'Toyota Buffaloes',
    'Google drive',
    'Mega milk',
    'Ventilated improved pit latrines'
  ],
  [
    'Nail clipper',
    'The great trek',
    'A design portfolio',
    'Uganda police',
    'Metroplex Naalya'
  ],
  [
    'Kasese',
    'Snap chat',
    'Google maps',
    'Government aided schools',
    'Hoover craft'
  ],
  ['Door mat', 'Pneumonia', 'Tilapia', 'Kitkat', 'Balck boards'],
  [
    'Smart boards',
    'Florescent tubes',
    ' Akena',
    'National language',
    'The flying squad'
  ],
  [
    'Temangalo',
    'Series Channel',
    'Mulnutrition',
    'Chief Executive officer',
    'Illusions'
  ],
  [
    'Bridal magazine',
    'Game stores',
    'PCB',
    'The northern by-pass',
    'The standard gauge railway'
  ],
  [
    'Bony katatumba',
    'Salt shaker',
    'Salt bae',
    'The golf course hotel',
    'Rebecca Kadaga'
  ],
  [
    'The Mercedes Benz',
    'Kadongo kamu',
    'Indian Ocean',
    'Endometriosis',
    'Live stalk farming'
  ],
  [
    'Holy Communion',
    'Downtown Owino',
    'Pakalast',
    'Inspector General of Government',
    'USSR'
  ],
  [
    'Martial arts',
    'Aerospace engineering',
    'Addidas',
    'The Genesis',
    'Nile Bank'
  ],
  [
    'Trash talker',
    "Sula's rolex",
    'Igongo cultural centre',
    'Mr. Waabit',
    'Bruce Lee'
  ],
  ['Nissan', 'Grocery store', 'Namib desert', 'Ginger bread', 'Donald Trump'],
  [
    'Old is gold',
    'Police pickup',
    'Fresh Dairy',
    'Lever',
    'Fang Fang restaurant'
  ],
  [
    'Graduation gouns',
    'Milutin Sredojević',
    'Brazilian hair',
    'Club Venom',
    'Idi Amin'
  ],
  ['Sky diving', 'Polygamy', 'The DAB', 'Legos', 'The Lego movie'],
  [
    '3D printer',
    'Bob Marley and the Wailers',
    'Arnold Schwarzenegger',
    'Rift valley railway',
    'Raum'
  ],
  ['Gaetano', 'Kanyamunyu', 'Busy signal', 'Windows', 'Nssf'],
  ['Oil refinery', 'Watoto', 'Knights', 'Kcca', 'Dwayne Johnson'],
  [
    'Subaru Forester',
    'Bull shit',
    'Black bell',
    ' Kisanja hakuna mchezo',
    'Barclays Bank'
  ],
  ['Pokemon', ' Onyango', 'Gps Coordinates', 'Cereal bowl', 'Huawei'],
  ['Apollo Hotel', 'Déjà vu', 'Mombasa', 'Internet bundles', 'Honey combs'],
  ['91.3 capital fm', 'Raka raka dance', 'cell', 'EALA', 'Bachwezi '],
  [
    'Laundry basket',
    'Spear Motors',
    'Centenary Park',
    'King Shaka',
    'Orbit chewing gum'
  ],
  [
    'Tamenaibuga dance',
    'A Zipper',
    'Landscape artists',
    'Ghost busters',
    'Handle with care'
  ],
  ['Wrestlemania', 'Malaria', 'UNRA', 'Paka Paka', 'Akembe dance'],
  [
    'Saida Kaloli',
    'Lake Kyoga',
    'Kisaasi',
    'kololo airstrip',
    'Namagunga Secondary'
  ],
  [
    'Tetris',
    'Courts of law',
    'Union Jack',
    'Grand imperial hotel',
    'Diski football'
  ],
  ['Nursery rhymes', 'Sudhir Ruparelia', 'Iron bar', 'BET', 'James corden'],
  [
    'Muchomo',
    'iron bars',
    'Selective reabsorption',
    'Gaetano Kaggwa',
    'Speed bumps'
  ],
  ['Inzkuri', 'The Egyptians', 'Red Banton', 'Leap of faith', 'Quatar airways'],
  [
    'Sweat glands',
    'Gayaza high school',
    'Fixed deposit accounts',
    'Olduvai gorge',
    'Sony bravia'
  ],
  [
    'The croods',
    'Ugandan Potholes',
    'Michael Jordan',
    'Eddy Murphy',
    'Inspector Gadget'
  ],
  [
    'Transgender',
    'Kibimba rice',
    'Nile casino',
    'Cham Towers',
    'Public sensitisation'
  ],
  [
    'Blood donor',
    'A Rolex kiosk',
    'Port Malaba',
    'White water rafting',
    'The human brain'
  ],
  ['Goliath', 'Weighing scale', 'Arua', 'The Kampala sun', 'Records']
];
