/* tslint:disable */

// this file is autogenerated

export default [
  ['Easter Monday', 'Mufasa', 'cityoil', 'Kifeesi', 'Sticky keys'],
  ['Temangalo', 'Jinja Town', 'Kevin Hart', 'Multichoice', 'Grand theft auto'],
  [
    'Mama Fiina',
    'Kasubi tombs',
    'Capital Shoppers',
    'Betty kamya',
    'Bachwezi '
  ],
  ['Obote', 'Reggae music', 'NFL', 'Midcom', 'Pelican'],
  ['Basoga', 'Fala', 'Donkey Kong', 'The blood moon', 'Nile Perch'],
  ['Shoprite', 'Methane gas', 'Teso', 'Kawempe', 'Speke resort munyonyo'],
  ['Instagram', 'Kiwi', 'The River Nile', 'Beams', 'Hima cement'],
  ['rafters', 'Premio', 'Gadafi', 'Game', 'Emmanuel Tumusime Mutebile'],
  ['Ssese Islands', 'Rolex', 'Safe boda', 'Kikumi kikumi', 'Allan Kasuja'],
  [
    'The standard gauge railway',
    'columns',
    'The world atlas',
    'The DAB',
    'Saint'
  ],
  ['Uganda Telecom', 'Nssf', 'Picasso', 'Karamajong', 'Queen of katwe'],
  ['Kcca', 'Bamuda triangle', 'TVO', 'Lake Albert', 'Nido'],
  ['UB40', 'kakise', 'Crime preventers', 'Mamba', 'Mirinda'],
  ['Mobile money', 'Club Amnesia', 'Alteeza', 'Justice league', 'MTV'],
  ['Andrew Mwenda', 'Isis', 'roof', 'Paddle', 'Early man'],
  ['UNRA', 'Pajero', 'Friday Night Lights', 'Red Indians', 'Total'],
  [
    'land lord',
    "Saint Mary's Kisubi",
    'Gaz',
    'Intern doctors',
    'Edward Kale Kayihura'
  ],
  ['Sudhir', 'Ziggy Marley', 'Mauritania', 'Pintrest', 'Garden Tea'],
  ['City Oilers', 'Kosovo', 'interior design', 'A Locket', 'Dexters Lab'],
  ['DP', 'Karuma', 'Eddie Kenzo', 'iron bars', 'Mengo'],
  [
    'Piatto',
    'Zambian President',
    'Rwenzururu',
    'Manchester united',
    'Sphincter muscles'
  ],
  ['300', 'CECAFA 2010', 'SGS', 'Suicide squad', 'CHOGM'],
  ['Umeme', 'metal plates', 'musisi', 'Mnet', 'Bruce Lee'],
  ['Noddles', 'Red', 'Donald Trump', 'Larakaraka', 'Irene Namubiru'],
  ['Daddies', 'Maradona', 'Tip Top Bread', 'apartments', 'Muwogola dance'],
  ['Digimon', 'Diarrhoea', 'James bond', 'Asus', 'Steve Jobs'],
  [
    'Inspector Gadget',
    'Sonic the Hedgehog',
    'Mubs',
    'Daffy Duck',
    'Steven Kavuma'
  ],
  [
    'Bukedde',
    'Kampala Carnival',
    'Garden city',
    'Wanchekecha',
    'Amabere ya Nyinamwiru'
  ],
  ['Mukwano', 'Paul Walker', 'Cheat codes', 'Matooke', 'Cool cool bar'],
  [
    'Pemba Warriors',
    'Benjamin Odoki',
    'Door stoppers',
    'Yusuf Lule',
    'Jackie Chan'
  ],
  ['False prophets', 'Phantom zone', 'Bull', 'Radio and Weasel', 'naalya'],
  ['Soweto', 'Super dip', 'Kofi olomide', 'Gaetano', 'engineers'],
  ['UPC', 'Doom', 'Yosemite Sam', 'Bujagali falls', 'Mount Kadam'],
  ['Nakawunde', 'Blu 3', 'Jacob', 'Highland water', 'Tea party'],
  ['Red Banton', 'Jean Claude Van Damme', 'Proton', 'Muzungu', 'Traffic jam'],
  [
    'Rubber',
    'Hajji Nasser ntege Ssebagala',
    'The Ebonies',
    'Insomnia',
    'A quest'
  ],
  ['Buganda', 'Second Chance', 'Anne Kansime', 'architects', 'Chinue Achebe'],
  [
    'Runyege and Entongoro dance',
    'Lugogo Cricket Oval',
    'Capital FM',
    'Macos',
    'Diarrhoea'
  ],
  ['Nickelodeon', 'Mozambique', 'Lamy', ' David Beckham', 'Bbale Francis'],
  [
    'Kampala Restaurant Week',
    'Mosese Magago',
    'KCCA carnival',
    'Core',
    'Lido Beach'
  ],
  [
    'Gaeton Kagwa',
    "That's Life Mwatu",
    'Sweet Pepsi',
    'Bean weavals',
    ' The great Pyramids of Giza'
  ],
  ['Nile Bank', 'plaster', "The LRA's Kony", '256', 'Autodesk'],
  [
    'Green star',
    'Back hoe',
    'Badru Kigundu',
    'Apple',
    'Habari , kabi , danger'
  ],
  [
    'Nokia tune',
    'New Zealand',
    'Hypocritical analysis',
    'fabrication',
    'Ipsum'
  ],
  [
    'National Water and Sewerage Corporation',
    'The Lego movie',
    'Gipir and lobongo',
    'Nokia',
    'Namib desert'
  ],
  ['Duracell', 'Teletubbies', 'Leap of faith', 'Kaloodo', 'Malwa'],
  [
    'pregnant',
    'A walk in closet',
    'Iyingo',
    'The Black Mambas',
    'Evander Holifield'
  ],
  [
    'Kadongo Kamu',
    'Nile Special',
    'Ajono(Malwa)',
    'Pittsburgh steelers',
    'Macarena'
  ],
  ['Moses', 'Nail clipper', 'North bridge', 'Mt muhavura', 'Michael Jordan'],
  ['Casablanca', 'UNRWA', 'Grip gloves', 'Barcelona FC', 'Tutankamun'],
  ['Daily Monitor', 'Madagascar', 'Kazire', 'Pascal', 'Mark Zuckerberg'],
  [
    'Uganda Revenue Authority',
    'Generations',
    'Kigali',
    'Ngongoro Crater',
    'Luzira upper prison'
  ],
  ['Christians', 'MoneyGram', 'Fay', 'Luke Skywalker', 'Dwayne Johnson'],
  ['Black Mamba', 'Luwombo', 'Shisha', 'Daudi Ochieng', 'Isuzu'],
  ['ufo', 'Kurosaki ichigo', 'Zero grazing', 'Big Brother Africa', 'Dr. Bosa'],
  [
    'German shepherd',
    'Civil Aviation Authority',
    'Eminem',
    'In heavens no beer',
    'Cameroonian'
  ],
  [
    'The hostel',
    'Janet Kataha Museveni',
    '1900 Buganda Agreement',
    'Lubiri',
    'Motherboard'
  ],
  ['The embassy', 'Spiderman', 'Rwenzori', 'Semei Kakungulu', 'Wilson'],
  ['Idi Amin', 'Coffee spirit', 'Kobs', 'manhole', 'Big O'],
  [
    'Rwot Kweri',
    'Government aided schools',
    "Air Jordan's",
    'Giggles',
    'Nail clippers'
  ],
  ['Coffee shop', 'Fotogenix', 'septic', 'Horse shoe', 'Emperor Olando'],
  ['OO7', 'Nakumatt', 'Celtel', 'Ggaba beach', 'Simplex network'],
  [
    ' Goal line technology',
    'Lord of the rings',
    'Bake',
    'Groot',
    'Bakayimbira Drumactors'
  ],
  [
    'Africell',
    'Jehover witness',
    'Auckland',
    'things fall apart',
    'The X factor'
  ],
  ['Scaffold', 'Mamdani', 'Night dancers', 'Kasese', 'Kintu'],
  ['Jughead', 'Morgan Trainer', 'Serena', 'Hipsters', 'UEB'],
  [
    'Cadbury',
    'The Democratic Republic of Congo',
    'Ben Kiwanuka',
    'Kololo',
    'Kyadondo Rugby Club'
  ],
  ['Pompeii grill', 'Sigiri', 'Garden Tea', 'CPU', 'Interior designers'],
  [
    'Paka Paka',
    'Ugly Duckling',
    'The Hulk',
    'Kangaroo jack',
    ' General Biraro'
  ],
  [
    'Kiwi',
    'PCB',
    'Fang Fang restaurant',
    'The human brain',
    'The kyoola solar bus'
  ],
  ['Hotel Africans', 'Sheebah Kalungi', ' Anslem', 'Flamingo', 'Fraud'],
  ['Bantu', 'Ebola', 'Monica Lowinsky', 'Catholicism', 'Legos'],
  ['Masaka road', 'Education', 'Tito Lutwa', 'Ivory Tower', 'The Genesis'],
  ['3D printer', 'DFCU', 'The landlord', 'Union Jack', 'Mwenge bigere'],
  ['casting', 'plan B', 'Ultrasound machine', 'Swangz Avenue', 'Crested Crane'],
  ['Ekizino dance', 'Kane and Abel', 'Mun G', 'Captain Planet', 'Guvnor'],
  ['Internet bundles', 'Vitruvius', 'Gonja', 'Kabale', 'Postbus'],
  [
    'Africa',
    'Roofings',
    '91.3 capital fm',
    'NDA (non disclosure agreement)',
    'Northern bypass'
  ],
  [
    'Victoria University',
    'Morgan Feeman',
    'Oil refinery',
    '2016 Presidential elections',
    'Buganda Road Primary School'
  ],
  ['Public sensitisation', 'Dead party', 'Yaka', 'Corolla', 'Ok Google'],
  ['KFC', 'Maurice Kirya', 'Hewlett-Packard', 'Colgate', 'Katumba wamala'],
  [
    'Tamarai',
    'Cannabis',
    'Stucco paint',
    'Handle with care',
    "Chameleon's tongue"
  ],
  ['Namirembe Cathedral', 'Jackie Chandiru', 'Tunis', 'Pillows', 'Bobi wine'],
  ['Brood', 'Agataliko Nfuufu', 'Rwanda', 'Lever', 'Mutation'],
  [
    'Apollo Hotel',
    'Wandegeya',
    'Samuel L. Jackson',
    'Maggie Kigongo',
    'Kyambogo university'
  ],
  [
    'Kendrick Lamar',
    'Pit latrine',
    'The accountant',
    'KPMG',
    'Makerere university'
  ],
  ['Samurai x', 'Bismilah', 'Maso awo ', 'Omweso', 'The Gaddafi mosque'],
  ['Case clinic', 'CNN', 'Drone', 'Game nights', 'Quality Supermarket'],
  ['Oxygen', 'Othello', 'Lady and the Tramp', 'Supersport Blitz', 'Owl city'],
  ['Oryx', 'marie curie', 'Oasis mall', 'Cardboard', 'Sanyu FM'],
  ['Bukedde TV', 'Albert Einstein', 'Stone Cold Steve Austin', 'PLE', 'Ne-yo'],
  ['Santa', 'A Zipper', 'Sharpie', 'The Globe', 'Quencher'],
  [
    'magma',
    'Landscape artists',
    'Transistor',
    'Invaka Trump',
    'Patrick idringi'
  ],
  [
    'Uganda Management Institute',
    'Typhoid',
    'Holy Communion',
    'Mulago hospital',
    'Kings college Budo'
  ],
  ['Adungu', 'xmen', '2001 Space Odyssey', 'TV chicken', 'Kawunda suit'],
  [
    'Downtown Owino',
    'Delta air',
    'Uganda Broadcasting Corporation',
    'Leica',
    'Fort Jesus'
  ],
  ['King Fahd Plaza', 'Hi vis vest', 'AON', 'Vuzu Tv', 'The Pearl of Africa'],
  [
    'Alex Ndawula',
    'Bell Lager',
    'Rock Paper Scissors',
    'Namilyango College',
    'Ludacris'
  ],
  [
    'Teenage Mutant Ninja Turtles',
    'Line of symetry',
    'Kalo',
    'Washing machine',
    'Precision Air'
  ],
  [
    'Mpenkoni',
    'Pokemon',
    'The Nile crocodile',
    'Lady Gaga',
    'The Daily mornitor'
  ],
  ['Old taxi park', 'Channel O', 'Bwola dance', 'Dell computers', 'Katwe'],
  ['KPC', 'The alpha', 'Quencher', 'Whatsapp', 'magnet'],
  ['The green light', ' Kisanja hakuna mchezo', 'Omo', 'Viber', 'Google'],
  [
    'Kansanga Miracle Centre',
    'Wrist watch',
    'Ennanga',
    'Energizer',
    'Pioneer mall'
  ],
  ['All Saints Cathedral', 'Detol', 'Mars', 'Agwara', 'The leopard'],
  [
    'Nile casino',
    'mukiibi lawrence',
    'Bon Apetit',
    'Angels and Demons',
    'Sedimentary rocks'
  ],
  [
    'Kintu and Nambi',
    'Justin Beiber',
    'Kampala Carnival',
    'Bungee jumping',
    'Bwaise'
  ],
  ['Walumbe', 'construction', 'The omuzinga', 'AC Milan', 'Kasoli'],
  ['Rav4', 'Sound of music', 'Coach Carter', 'Honey moon', 'Irene brake'],
  [
    'Shimoni Primary Shool',
    'Sponge Bob',
    'Nike frees',
    'Solar Eclipse',
    'YMCA'
  ],
  [
    'Christian Bale',
    'Pope Francis',
    'Miley Cyrus',
    'The pyramids',
    'Uganda airlines'
  ],
  ['Pneumonia', 'Chuck Noris', 'Nikon', 'Yoweri Kaguta Museveni', 'Kati Kati'],
  [
    'Diamonds',
    'Lake Tanganyika',
    'Grand imperial hotel',
    'Balokole',
    'Cheese bread'
  ],
  [
    'Janet Museveni',
    'Subaru',
    'Hannah Montana',
    'The Niagara falls',
    'Paul kafeero'
  ],
  [
    'Queen Elizabeth',
    'Central business district',
    "5 1/2' floppy disc",
    'Irene ntale',
    'Quatar airways'
  ],
  [
    'Kizza Besigye',
    'Gayaza high school',
    'family guy',
    'Tororo Rock',
    'Vintage cars'
  ],
  ['Sprint', 'Sudhir Ruparelia', 'Obey your thirst', 'Barclays', 'Ykee Benda'],
  [
    'Uganda House',
    'Soulja Boy',
    'Kevin Systrom and Mike Krieger (instagram founders)',
    'A blogger',
    'Long horned cattle'
  ],
  ['Anita Fabiola', 'Cinderella', 'King Oyo', 'Facebook Messenger', 'Kalooli'],
  [
    'Bad Brown',
    'Eiffel tower',
    'Ludo',
    'Friday the 13th',
    'Capital Shoppers promotion'
  ],
  ['Pancakes aka', 'Ford', 'Adolf Hitler', 'Patwa', 'residence'],
  [
    'Savero',
    'Martin Luther King',
    'Kilembe Mines',
    'Uganda Silverbacks',
    'Butcherman'
  ],
  ['Barack Obama', 'Linux', 'Mine Boy', 'West Nile tribe', 'Portbell'],
  [
    'Oliver Twist',
    'Malcom X',
    'The synagogue church',
    'Ketchup',
    'Namagunga Secondary'
  ],
  ['COMESA', 'Mohamad Ali', 'Mirinda fruity', 'A submarine', 'Mt. Rwenzori'],
  ['Ghetto President', 'The acacia place', 'UPE', 'Tuskys', 'Mt. Elgon'],
  [
    'Piato',
    'Lake Kagera',
    'Robert Kiyosaki',
    'The Ministry of Foreign Affairs',
    'Mechanised systems'
  ],
  [
    'Bullet proof vests',
    'Bendicto Kiwanuka',
    'Century Cinemax',
    'Michael Jackson',
    'Specioza Kazibwe'
  ],
  [
    'NBS',
    'Edward Mutesa',
    'Shakes Fimbo',
    'Sega Dreamcast',
    'Texas Instruments'
  ],
  ['NTV', 'Phanero', 'Professor x', 'iryn namubiru namugongo', 'Jinja'],
  [
    'Endometriosis',
    'Dumpy level',
    'Carbon copy',
    'Humps ahead',
    'The Big Five'
  ],
  ['Fanta Fruit Blast', 'Pimp', 'Dell optiplex', 'Louvres', 'Owen falls dam'],
  ['Moreen kyalya', 'Jesa', 'Trevor Noah', 'African crafts', 'Ray Charles'],
  [
    'Cool cool bar',
    'AIDS',
    'Land of milk and honey',
    'Kodak',
    'Masaka-mbra highway'
  ],
  [
    'Magnetic flux density',
    'HIV',
    "That's life mwatu",
    'Kobe Bryant',
    'Kiss of death'
  ],
  [
    'Ghost busters',
    'Mosquitoe',
    'Bat valley theatre',
    'Gaetano kagwa',
    'Lenovo'
  ],
  [' Cleopatra', 'Cake', 'Theatre la Bonita', ' Onyango Obbo', 'Munyonyo'],
  [
    'Bald',
    'Uganda cancer institute',
    'Spectrum',
    'Abraham',
    'Fitness trackers'
  ],
  [
    'Cairo international bank',
    'Besigye',
    'Rick dees and americas top 40',
    'January',
    'Clay pots'
  ],
  [
    'The East African Community',
    'Kasangati',
    'Ebee',
    'Forex exchange',
    'The Daily Monitor'
  ],
  [
    'The Common Markets for East and Southern Africa (COMESA?)',
    'Janan Luwumu',
    'Molokony',
    'Dictionary',
    'otada'
  ],
  ['Brittania', 'Isaac Newton', 'Vladimir Putin', 'Caterpillar', 'An Apache'],
  [
    'Source of the nile',
    'Poker face',
    'Ekitaguriro dance',
    'Beast Wars',
    'Toyota'
  ],
  ['Sony Playstation', 'Inzkuri', 'Lcd', 'Splash', 'Kampala golf course'],
  ['Pick n Peel', 'James corden', 'Tsetsefly', 'Kiira EV', 'Shopping voucher'],
  [
    'Tip Top Bread',
    'The Beatles',
    'Margaret Trowel school of fine art.',
    'Buglar proofing',
    'Xfm'
  ],
  [
    "St mary's Kitende",
    'Micheal Jackson',
    'Peer groups',
    'Ethiopian Airways',
    ' Music dance and drama'
  ],
  ['Fresh Dairy', 'NRM', 'Green water', 'Jet ski', 'PTSD'],
  ['Head lamps', 'Mabira forest', 'Kanungu', 'Barber Shop', 'Nokia katochi'],
  ['The rich also cry', 'Accra', 'Kibwetere', 'Valentine', 'Kitoko'],
  [
    'Uganda Coffee Development Authority',
    'zari',
    'Lakwena',
    'Game stores',
    'The national theatre'
  ],
  [
    'Bugolobi Flats',
    'Rukidi IV of Toro',
    'Amakondeere',
    'Tusker project fame',
    'Nairobi'
  ],
  ['Bukoto Flats', 'Water slide', 'Landline', 'Kamu Kamu plaza', 'Red Pepper'],
  [
    'Acacia Mall',
    'Nice clear',
    'Charles Darwin',
    'Gameboy color',
    'Kisoro district'
  ],
  ['Village Mall', 'Jukebox', 'Mulnutrition', 'Game zone', 'Terminator'],
  [
    "Worker's House",
    'Swimming pool',
    'Embooli',
    'Christian fellowships',
    'Kawunyemu'
  ],
  [
    "Communication's House",
    'Southampton.',
    'The dictator',
    'Burkina Faso',
    'Robert Downey junior'
  ],
  [
    'Parliament Avenue',
    'Riham biscuits',
    'Blu-ray disc',
    'Presidential handshake',
    'Tony stark'
  ],
  ['Cheer leaders', 'Ubc', 'Semliki National Park', 'Bed wetters', 'Tilapia'],
  [
    'Ankara',
    'Psquare',
    'Bob Marley and the Wailers',
    'Chris Adams',
    'Vj jingo'
  ],
  [
    'South Sudan',
    'Power puff girls',
    'Ventilated improved pit latrines',
    'Kabalagala',
    'Ewe'
  ],
  ['Gnl', 'Apeta', 'The avengers', 'Poker Face', 'Mountain Moroto'],
  [
    'The Adventures of TinTin',
    'Lexus',
    'Watoto Church',
    'Lake Victoria',
    'Ginger bread'
  ],
  [
    'George of the Jungle',
    'The Mighty Morphin Power Rangers',
    'Tesla',
    'city parents',
    'Afcon'
  ],
  [
    'Solex padlock',
    'Lake Kyoga',
    'Nice house of plastics',
    'Weed',
    '[22:13, 2/27/2017] +256 702 204609: Logitech'
  ],
  ['Lake Bunyonyi', 'Ange noir', 'TATA', 'Haris international', 'Theodolite'],
  ['Erias lukwago', 'Lugogo Mall', 'Broke', 'Binding wire', 'Zanzibar'],
  ['UTL Mango', 'Agnes Nandutu', 'Dubai', 'Happy hour', 'BETWAY'],
  ['Ear plugs', '9 lives', 'One by one', 'Forex Bureau', 'Nissan'],
  ['Centenary Park', 'Gorillos', 'Mehta', 'Bruno Mars', 'Arabica coffee'],
  ['Rugby', ' Nefertiti', 'Dar-es-salaam', 'FUBA', 'face technology'],
  [
    'Club Ambiance',
    'The Ministry of Finance',
    'FUFA',
    'The Republic of Tanzania',
    'Glazing'
  ],
  [
    'Mountain Elgon',
    'American dad',
    'Silicon chips',
    'Mouse trap',
    'Sama-saulting chicken'
  ],
  [
    'Lithium ion batteries',
    'Mweya safari lodge',
    'Winter is coming',
    'Kabaka Mutebi',
    'Namboole Stadium'
  ],
  ['Equity bank', 'Steven Spielberg', '50 First Dates', 'Big G', 'Malaria'],
  ['Scrabble', 'Milk', 'Gattomato', 'Lake katwe', 'Remote'],
  ['Tecno', 'Express FC', 'Marvin Gaye', 'Kobil', 'Kitante Primary School'],
  ['Forest Mall', 'Ofwono', 'Angelina Jolie', 'Hot loaf', 'Shower gel'],
  [
    'Wembley stadium',
    'Bob Marley',
    'Morogoro',
    'World Wrestling Federation',
    'geoffrey massa'
  ],
  ['Pope John Paul II', 'Cisco', 'Wedding Meeting', 'Micho ', 'Déjà vu'],
  [
    'Mohamad Nseroko',
    'Zoom Club',
    'Posho and beans',
    'The book of wisdom',
    'Carpool'
  ],
  [
    'Metroplex Naalya',
    'Henry Newton',
    'The Dukka',
    'Mccauley Culkin',
    'Ham Towers'
  ],
  ['Miya farouk', 'Debanj', 'Shoe', 'Mukene', 'Tamale mirundi'],
  ['White ants', 'Lugabile', 'Agha Khan', 'mulindwa lawrence', 'Diskette'],
  [
    'Kansanga',
    'Fela',
    'Shaggy',
    'Wizkid',
    'Ekitobero a la carte (double check that spelling)'
  ],
  ['Vienna College', 'Katanga', 'Kakande', 'BomberMan', 'Gen Katumba Wamala'],
  ['Sitya loss', 'Delident', 'Merry-go-round', 'Salim Saleh', 'CBS'],
  [
    'Friendship taxi',
    'Night prep',
    'William Obote',
    'Marie Antoinette',
    'Dasani'
  ],
  ['Glazing', 'Vienna', 'Spalding', 'Dunlop', 'Sony Walkman'],
  [
    'The Republic of Kenya',
    'Fastjet',
    'Mozilla',
    'Betway Kobs',
    'Air force one'
  ],
  [
    'Mandazi',
    'Animal farm',
    'Previously on',
    'We will not wait for karamoja to develop',
    ' Kowtow in their poohoo'
  ],
  [
    'Snow white and the seven dwarfs',
    'Pablo',
    'Burundi',
    'kololo airstrip',
    'Chameleone'
  ],
  ['Judaism', 'Italia', 'Bell lager', 'Wanale', 'Passengers'],
  [
    'Golden State Warriors',
    'Crane bank',
    'Vulnerable persons',
    'Public holiday',
    'Pablo Escobar'
  ],
  ['Kadashians', ' Onyango', 'Weetabix', 'Friday nights live', 'Aristoc'],
  ['Kale Kayihura', 'Nike', 'Mt Kilimanjaro', 'Breakfast and bed', 'Makerere'],
  ['KLM', 'Indian Ocean', 'Time traveller', 'Migingo Island', 'Mombasa'],
  ['Uhuru', 'Silver Springs Hotel', 'Butabika', 'TASO', 'Gulu town'],
  ['Morgue', 'Tyson Waragi', 'Bhagdad', 'Doris Akol', 'Owen Falls Dam'],
  [
    'Wandegeya chicken',
    'Nandos',
    'Cumulative frequency',
    'The friend zone',
    'The holy trinity'
  ],
  [
    'Winterland',
    'The nervous system',
    "Dr. Shaque O'Neal",
    'Iron bar thugs',
    'NASA'
  ],
  ['Stone Town', 'Uganda national anthem', 'Polo', 'Arusha', 'Mr IBU'],
  ['Woodball', 'Clock tower', 'Ak-47', 'Golf', '1000 ways to die'],
  [
    'Trash talker',
    'Arua',
    'Gaddafi',
    'The secret life of bees',
    'The northern by-pass'
  ],
  ['Tullow Oil', 'KIU Titans', 'Linkin park', 'Jumia', 'Bata'],
  [
    'Borosilicate',
    'Kampala International School Uganda',
    'Iris',
    'Star Wars',
    'Martial arts'
  ],
  ['Chapati', 'Graduation gouns', 'Stanley Ntagali', 'soak pit', 'Ice age'],
  [
    'River orange',
    'Uganda police',
    'The ten commandments',
    'Sese gateway Beach',
    'John 3:16'
  ],
  [
    'Al Shabbab',
    'Margarine',
    'Swissgarde',
    'Godfrey Massa',
    'Davis and Shirtliff'
  ],
  ['Marco Polo', 'Photoshop', 'Irongo dance', 'Constantine', 'Lake Malawi'],
  ['cell', 'Queen bee', 'Pedlum Bob', 'Busy signal', 'PK'],
  [
    'Middle East consultants',
    'Mwanga dance',
    'Stella Nyanzi',
    'Liquid Silk',
    'Steve Jobs'
  ],
  ['Age of empires', 'LinkedIn', 'Autumn', 'Sheebah', 'Polygamy'],
  [
    '[16:05, 2/27/2017] +256 702 204609: 9th October 1966',
    'Beans',
    'Dexter',
    'The observer',
    'Sansa'
  ],
  [
    'Nvidia graphics card',
    'atin paco',
    'Four cousins',
    'Blood donor',
    'Bird flu'
  ],
  ['Rwenzori Mountains', 'Pepe Kale', 'Liquid soap', 'Spelling bee', 'Whore'],
  [
    'Sekitulege',
    'Nawab Asian Bistro',
    'Ugly Betty',
    'Balck boards',
    'Sony vaio'
  ],
  ['Barcelona', 'Engalabi', 'JFK', 'kalita', 'Renault'],
  ['Christmas', 'Endingidi', 'Street Fighter', 'Seya ', 'Monopoly'],
  [
    'Mukwano cooking oil',
    'Hewlett Packard',
    'Timothy',
    'Oil And petroleum',
    'Club Venom'
  ],
  ['The Egyptians', 'The Kyabaziga', 'Sony bravia', 'Esau', 'Olduvai gorge'],
  ['Life is good', 'Home run', 'Akadinda', 'Bugs Bunny', 'Toy Story'],
  [
    'Dairy farming',
    'Kitchen ware',
    'Rebecca Kadaga',
    'URA FC',
    'The lion king'
  ],
  ['The Kampala casino', 'Rig', 'St. Augustin', 'Uber', 'Greenlands Bank'],
  ['Navio', 'Kyadondo rugby grounds', 'Chapatti', '350 mls', '4G'],
  ['Smigo', 'Uganda railway', 'Arusha', 'Posho', "G4s McDonald's"],
  ['Chameleon', 'Boda boda', 'The Kampala sun', 'Fake hair', 'Muchomo'],
  ['Samsung galaxy note 4', 'Timber', 'Nyama', 'Boda', 'Tommy Hilfiger'],
  ['Pombe', 'Airtel', 'Aladdin', 'Dodo', 'System unit'],
  [
    'New taxi park',
    ' Cristiano Ronaldo',
    'Cool cool bar',
    'Wine',
    'Cham Towers'
  ],
  ['Caffesserie', 'Bogoya', 'Aristoc', 'Lake View Hotel', 'Internet explorer'],
  ['Morgan Freeman', 'Addidas', 'Condom', 'Club Play', 'Bushera'],
  ['Jetlee', 'Punch cards', 'Muhammad Ali', 'Sadolin paints', 'Scratch proof'],
  ['Unilever', 'Eagles band', 'Kabaka Mwenda Mutebi II', 'Omo', 'Pokemon'],
  ['Musaawo', 'Jessica Alba', 'Matatu', '1 Million', 'Nankasa dance'],
  [
    'Bill Gates',
    'Standard chartered Bank',
    'ITunes',
    'Acholi',
    'Bridal magazine'
  ],
  ['Rotten Tomatoes', 'Winter', 'Jim Muhwezi', 'Netflix', 'Clouds'],
  [
    'Binding tape',
    'Black sheep affair',
    'Every where you go',
    'Endere',
    'Mirror Mirror on the wall'
  ],
  ['GPS', 'Simba FC', 'The notebook', 'Records', 'Blue 3'],
  [
    'Ninja worrier',
    'Mississippi',
    'Nakasero market',
    'Aliko Dangote',
    'Windows'
  ],
  [
    'Mediterraneo Restaurant',
    'The undertaker',
    'The voice',
    'Youtube',
    'Lagos Naija'
  ],
  ['Chipoli', 'Toyota Buffaloes', 'The Easter bunny', 'The hobit', 'KIU'],
  ['Cassava', 'Lama', 'Mabirizi Complex', 'Gangnam Style', 'Katogo'],
  ['Stephen Omony', 'M23 rebels', 'Nze Nimiro', 'The barbarians', 'Tetris'],
  ['HP', 'Dubai', 'Ice ice baby', 'Sudhir Ruparelia', 'Lake kyoga'],
  ['Water proof', 'Guitar', 'Kampala', 'SC Villa', 'VGA'],
  ['Kenya Airways', 'Windows 3.1', 'Lights', 'Iron bar', 'Boeng'],
  [
    'Kampala Parents school',
    'Fly540',
    'Indiana Jones and the Last Crusade',
    'Shell',
    'The Ssese islands'
  ],
  ['Jimmy Enabu', 'Sodium carbonate', 'The prison break', 'Goodnight', 'Uzi'],
  [
    'Mandazi',
    'Hey there Delilah',
    'Denis Obua',
    'Entebbe International Airport',
    'East African development bank'
  ],
  ['UPDF Special Forces Command', 'Mirror', 'Renault', 'Mohhock', 'Alshabaab'],
  ['Bible house', 'Murchison falls', 'MTN', 'Gators Cafe', 'Zumba'],
  [
    'Everready',
    'Sky Lounge',
    'Chicoco',
    'The golf course hotel',
    "Valentine's day"
  ],
  ['Calculators', 'Lohnro Motors', 'Blind spot', 'KIA', 'Godzilla'],
  ['The arsenal massacre', 'EALA', 'Etihad stadium', 'Buduuda', 'Maths'],
  [
    'Startimes',
    'Adobe master collective suite',
    'GoTv',
    'The Mexico-usa border',
    'Wireless Fidelity'
  ],
  ['Endongo', 'Wine cork', 'Kanye West', 'Bank robbers', 'Invisible children'],
  ['Handle', 'Backtrack', 'Pope John Paul the 2nd', 'Mary Mary', 'Kigali'],
  ['Aerial', 'Nasser rd', 'The Nile', 'Kyanja', 'Guard rail'],
  [
    'Judith heard nalongo',
    'Kisaasi',
    'ABSA premier league',
    'Saida Kaloli',
    'Bugolobi'
  ],
  [
    'Diski football',
    'Usher Reymond',
    'Naguru',
    'Mapeera house',
    'Ronald Reagan'
  ],
  [
    'Protestant',
    'Inspector General of Government',
    'White water rafting',
    'FDC',
    'The championchampions league'
  ],
  [
    'Air Uganda',
    'Nakasero',
    'The 9th of October',
    'Serena Hotel',
    'Seychelles'
  ],
  ['Reptiles', 'December', 'Kampala Cocktail Week', 'War Dogs', 'Kafuunda'],
  [
    'Bruce Lee',
    'Grocery store',
    'Telegram',
    'Subaru Imprezza',
    'The grasshopper month'
  ],
  [
    'Ggaba beach',
    'The Pearl Guide Uganda',
    'Abuja',
    'Street art',
    'Land mines'
  ],
  [
    'Black bell',
    'Zara',
    'Weighing scale',
    'Quality chemicals ltd',
    'Sir Alex Ferguson'
  ],
  ['PPDA', 'The flying squad', 'Muzikiti', 'Jacob Zuma', 'Sangoma'],
  [
    'Human trafficking',
    'Jacob Oulanyah',
    'Beside',
    'Princes Diana',
    'Uhuru Kenyatta'
  ],
  [
    'City square',
    'Mozart Wolfgang',
    'Daniel Arap Moi',
    'Aronda nyakairema',
    'Picfare'
  ],
  ['Enteebe', 'The Joker', 'Umoja', 'Scribes', 'Dead shot'],
  [
    'The Serengeti',
    'Centenary Bank',
    'Fly on your own',
    'Spearmint',
    'Jackie chan'
  ],
  ['Canoes', 'Cherokee', 'Canon', 'Phillips', 'Kalo'],
  ['Kenyatta', 'Rwenzori Mineral Water', 'Tropical Heat', 'NBA', 'Black Swan'],
  ['Boxers', 'Desire Luzinda', 'Gym', 'Mitsubishi', 'Spa'],
  ['Casio', 'Pingu', 'Nissan Patrol', 'Cairo', 'Toyota Vitz'],
  ['Ms DOS', 'Toyota Corolla', 'R. Kelly', 'Subaru Forester', 'Lagos'],
  ['Uganda cranes', 'Anglican', 'Nandujja', 'Kakira Sugar', 'Will Smith'],
  ['Cineplex', 'Snowwhite', 'uganda museum', 'Kiprotich', 'Mr Bean'],
  [
    'Mega Standard Supermarket',
    'Mission Impossible',
    'Joe Bidden',
    'Samosas',
    'Stanbic Bank'
  ],
  ['Mt Kenya', 'Orient Bank', 'Greenland', 'Dfcu bank', 'Iceland'],
  [
    'Gipiri and Labong',
    'Queen Latifa',
    'Karamoja',
    'South Sudan',
    'Goloola Moses'
  ],
  [
    'Ferry',
    'Bella Wine',
    'London has fallen',
    'Oxford Mathematical Set',
    'Enkwanzi'
  ],
  ['Hallmark', 'Sky diving', 'Smart wire', 'The Simpsons', 'Taxi conductors'],
  [
    'Angry birds',
    'Luzira',
    'A Rolex kiosk',
    "god's must be crazy",
    'Smart boards'
  ],
  ['Ludo', 'Kick boxing', 'The Swiss alps', 'Inter Milan', 'Chuck Norris'],
  [
    'Mr. Kampala',
    'Uganda Chess Federation',
    'The great trek',
    'PAC (public accounts committee)',
    'Mufere'
  ],
  [
    'Sodium',
    'Highland mineral water',
    'John Akii-Bua',
    'Kadongo kamu',
    'National language'
  ],
  [
    'Shaulin soccer',
    'Caster Semenya',
    'Double A batteries',
    'Carriage way',
    'plumbers'
  ],
  [
    'Chief begger',
    'John speke',
    'Monalisa',
    'Pool Court',
    'The ugandan air force'
  ],
  [
    'Transcend',
    'Robbin island',
    "The Assassin's creed",
    'Brian Odong',
    'Sadolin'
  ],
  [
    'Uganda Waragi',
    'The Jackson Five',
    'Mosquitoes',
    'Stick bread',
    'Klashvinkov'
  ],
  [
    'KCCA FC',
    'Everywhere you go',
    'Alter wine',
    'Mean Machine',
    'Mahatma ghandi'
  ],
  ['Kololo airstrip', 'Malaba', 'MySpace', 'Moi', 'Jomo Kenyatta'],
  ['Crazy Cock', 'Juba', 'Earth, Wind and Fire', 'Acer', 'Designated survivor'],
  [
    'Zinjanthropus',
    'Akembe dance',
    'Hewlett Packard',
    'Mediterranean Sea',
    'Akamwesi hostel'
  ],
  ['Spellings', 'Land Cruiser', 'KFM', 'The smartphone network', 'Ihk'],
  ['Snapchat', 'Hair dye', 'iPhone 7', 'SMACK', 'Uganda clays'],
  ['Extension cable', 'Paintball', 'And1', 'Tigerhead', 'Air guitar'],
  ['PCL', 'Reebok', 'Bill Gates', 'Amazon Kindle', 'Macintosh'],
  [
    'Puss in boots',
    'Reid Hoffmann (LinkedIn founder)',
    'Kamyu',
    'Evan Spiegel (snapchat founder)',
    'Eddy Murphy'
  ],
  ['Kericho Tea', 'Java', 'Jeniffer Musisi', 'Kitkat', 'Science students'],
  [
    'Arsenal FC',
    'The Source of the River Nile',
    'Who killed captain Alex',
    'King Shaka',
    'Cable carts'
  ],
  [
    'Kabira country club',
    'Garlic stew',
    'Boxing gloves',
    'Amawulire',
    'Hoover craft'
  ],
  ['Fiji', 'The maple leaf', 'Panamera', 'Usain bolt', 'Milton Obote'],
  [
    'Bush Court',
    'Stephen Curry',
    'Beetleborgs',
    'Tamenaibuga dance',
    '[22:55, 2/27/2017] +256 773 106724: Community policing'
  ],
  [
    'Rwabushenyi Memorial Chess Championship',
    'Kidepo national park',
    'Solar cell',
    'Pakalast',
    'Sega Mega Drive'
  ],
  [
    'Tv Africa',
    'Work work work work',
    'Hashtag Rap',
    'The goatee',
    'Video Library'
  ],
  ['Atom', 'Simba Telecom', 'Alien ware', 'Midcom', 'Speke apartments'],
  ['Scotch', 'Gold', 'Sugar mommies', ' Meesi', 'KK Security'],
  [
    'Standard chartered',
    'Café javas',
    'Golola Moses',
    'The Lion King',
    'HTC phones'
  ],
  ['Beauty and the Beast', 'Kilimall', 'Lugogo Bypass', 'Floor traps', 'DHL'],
  ['Mouse traps', 'Fifa 2016', ' Ronaldo', 'Game of thrones', 'Kato Lubwama'],
  ["Sula's rolex", 'Sony Ericsson', 'EPL', 'Cheese', 'Google maps'],
  ['Olympus has fallen', 'LinkedIn', 'slabs', 'Karate Kid', 'Graphite'],
  ['Port Malaba', 'Kabaka Mwanga', 'Plot', 'Planet of the apes', 'A Wish list'],
  [
    'Micro SD card',
    'Austraia',
    'Terms and conditions',
    'Bbale Francis',
    'Kira motors'
  ],
  ['Winnie Nwagi', 'Poko poko', 'Akamba', 'Hima Cement Heathens', 'Ubuntu'],
  ['Jik', 'Ktv', 'Vim', 'Awillo Longoma', ' Okocha'],
  ['Halima', 'Margaret Thatcher', 'Ekyimbeewo', 'Kiwaani', 'Goliath'],
  [
    'Forest',
    'Volkswagen',
    'Uganda Manufacturers Association',
    'Ntinda',
    'Magufuli'
  ],
  ['Lumia', 'Home Alone', ' Kaihura nkuba', 'Robert Mugabe', 'Snake'],
  [
    'Certificate of appreciation',
    'Siri',
    'Barkcloth',
    'Nalufuka dance',
    'The Ministry of Health'
  ],
  [
    'Patrick Mbire',
    '24k magic',
    'Gordon Wavamuno',
    'Hwansung furniture',
    'Spear Motors'
  ],
  ['Saudi Arabia', 'The super bowl', 'Fa', 'Mitsubishi', 'Denzel'],
  [
    'Aerospace engineering',
    'Fragrance',
    'Kira Motors',
    'Porsche',
    'Easter Monday'
  ],
  [
    "Don't be like bro",
    'Aristoc',
    'Lady Gaaga',
    'Paint specifier',
    'Betty Nambozi'
  ],
  [
    'La Pattisserie',
    'Nakasero Primary School',
    'Kings of Leon',
    'Red Carpet',
    'Adungu dance'
  ],
  ['ABBA', 'Nawab Asian Bistro', 'Navigator', 'Royco', 'The Alchemist'],
  [
    'Kiboko',
    'This side up',
    'The Dark Knight',
    'Ssebagala and sons electrical supplies',
    'Stage (as in boda or taxi stage)'
  ],
  [
    'Bay watch',
    'Zone 7',
    'Rwandair',
    'The Ministry of Education and Sports',
    'wolverin'
  ],
  ['Flea', 'Chuck Bass', 'Vernier caliper', 'The Mercedes Benz', 'ISU'],
  ["Art's students", 'The Royal Guards', 'plan A', 'Hipster', 'Colour schemes'],
  ['Nail polish', 'Special effects', 'Shaggy', 'ABSA', 'Muna Kampala'],
  [
    'The Geneva peace convention',
    'Neyo',
    'The Kayola bus',
    'Made in china',
    'Neon'
  ],
  ['Power FM', 'Copper rods', 'Suits', 'Sunset beach', 'Wrestlemania'],
  [
    'Chicken brain',
    'Uganda Airways',
    'Fantastic Four',
    'Salvador',
    'Nokia 3310'
  ],
  [
    'Teenage Mutant Ninja Turtles',
    'State house',
    'Mulago referral hospital',
    'Kazinga Channel',
    'Etofali'
  ],
  [
    'Guvnor Night club',
    'SI unit',
    'Double glazed glass',
    'Emirates stadium',
    'Animaniacs'
  ],
  ['Emirates', 'Poker', ' Another rap', 'Leonardo di Caprio', 'Chelsea FC'],
  [
    'Roke Telekom',
    'Leceister FC',
    'Uganda National Bureau of Standards',
    'Real Madrid FC',
    'Kowtow in your poohoo'
  ],
  [
    'pipes',
    "King's College Budo",
    'Snowden',
    'concrete',
    'Cleveland Cavaliers'
  ],
  ['A wordrobe', 'Pringles', 'Hit man', 'Lebron James', 'Flat roof'],
  [
    'Snakes and ladders',
    'The QWERTY',
    'Wakaliwood',
    'Fresh diary',
    'Marabu stork'
  ],
  [
    'Virtual reality gear',
    'African Cup of Nations',
    'Idi Amin Dada',
    'Afrobasket Championships',
    'How I met your mother'
  ],
  ['Dorcus Inzikuru', 'Wall clock', 'Microsoft', 'The hub', 'Mambo number 5'],
  [
    'Jinja road',
    'Jose Morinho',
    'UV rays',
    'Special forces command (SFC)',
    'Last king of Scotland'
  ],
  ['Phablet', 'Ugandan girls', 'CCCC', 'Facebook', 'Zuena'],
  ['tanks', 'Call of Duty', 'Jacuzzi', 'Haka', 'Australia'],
  ['ISIS', 'The North Star', 'Gmail', 'Kiira town council', 'SADC'],
  [
    'Internet cafe',
    'Jazz Supermarket',
    'Old is gold',
    'Series Channel',
    'Sebagala and Sons'
  ],
  ['Purple Rain', 'A consul', 'Mercedes SLR', 'Star fish', 'Fanta Fruity'],
  ['Cold play', 'Namboole', 'Lugazi Sugar', 'BET', 'Ugali'],
  ['Wink', 'Bic', 'kakalambada', 'Bunsen burner', 'Dunhill'],
  [
    'Wine opener',
    'The New Vision',
    'Mountain Gorilla',
    'NBA 2016',
    'Full beam lights'
  ],
  ['Olx Uganda', 'Reset button', 'Boys 2 Men', 'Country music', 'Super Dip'],
  ['The davinci code', 'Illusions', 'Monot', 'Namugunga', 'WWE'],
  ['iTunes', 'Shrek', 'University professor', 'Coco sisters', 'Polygamy'],
  ['Gaetano Kaggwa', 'Chips and chaps', 'Kitengi', 'Sekanolya', 'Huawei'],
  ['Spacio', ' Game night is fun', 'Malaria', 'Habari', 'Chinese'],
  ['Muhammad Santur (spelling)', 'Omo', 'Lukaya', 'The croods', 'Mark x'],
  ['Geisha', 'American football', 'Iss', 'Napoleon Bonaparte I', ' Akena'],
  [
    'Kampala International University',
    'Beyoncé',
    'Flu shots',
    'Orbit chewing gum',
    'Spur'
  ],
  ['Ofwono bottle', 'Go cart racing', 'Internet', 'City Oil', 'Phillips'],
  ['Ruhakana Rugunda', 'Rock Boom', 'Taste the feeling', 'Red Bull', 'Dmark'],
  ['Weetabix', 'Guard rail', 'Muvule Tree', 'Alligators', 'Insurance broker'],
  ['A flight simulator', 'Apple pie', 'The School uniform', 'Honda', 'Yamaha'],
  ['9th October', 'Ducati', 'Janet Jackson', 'Power horse', 'Wbs'],
  [
    'Woolworths',
    'Kalangala',
    'Rainbow International School',
    'Lilian Mbabazi',
    'Chicken Tonight'
  ],
  ['Landrovers', 'Oseke', 'Juventus', 'John Magufuli', 'E! Entertainment'],
  ['Gap year', 'Raum', 'The us navy seals', 'Samurai', 'Telephone'],
  [
    'Bony katatumba',
    ' Light and sound show',
    'Nintendo 64',
    'Juliana Kanyomozi',
    'The exodus'
  ],
  [
    'The adventures of Tom Sawyer',
    'Nasser',
    'Bruce Willis',
    'Microsoft Xbox',
    'Nice Biscuits'
  ],
  [
    'Mega milk',
    'The omega',
    'Moses Ndiema Kipsiro',
    'Chlorine gas',
    'The London eye'
  ],
  ['BBC', 'Song of Lawino', 'Tripod stand', 'Low battery', 'Pete Sampras'],
  ['Owino market', 'Need for speed', 'Fatboy', 'Curfew', 'Rush Hour'],
  [
    'The big bang',
    'East African Reggae Bashment Crew',
    'Fresh Prince of bellair(not sure of the spelling)',
    'Auto correct',
    'Kikomando'
  ],
  ['Siri', 'Cortana', 'Syschelles islands', 'Raila Odinga', 'The East African'],
  ['UNEB', 'Browser history', 'Godrey Binaisa', 'Wisdom tooth', 'Sheraton'],
  [
    'Civil aviation authority',
    'foremen',
    'Kimberly mines',
    'Wavah water',
    'Service duct'
  ],
  [
    'Express FC',
    'Java House',
    'samsung',
    'Paul Kagame',
    'The Department of justice'
  ],
  [
    'Salivary glands',
    'Bad black',
    'Selective reabsorption',
    'Gps Coordinates',
    'Lamp post'
  ],
  [
    'Uhuru kenyatta',
    'A burger meal',
    'Burger King',
    'Olanya Colombus',
    'Loubega'
  ],
  ['Bebe Cool', 'Lady Cranes', 'Poker face', 'Coffee mug', 'Back hoe'],
  [
    'U-turn',
    "As thin as radio's arms",
    'Greenland Bank ',
    'Linen cloth',
    'Noor'
  ],
  ['Silk Royale', 'Bedbug', 'Arse', 'Adam Sandler', 'Google drive'],
  [
    'Louvered vents',
    'The Etihad',
    'Mr. Waabit',
    'Popcorn',
    'A design portfolio'
  ],
  [
    'A company profile',
    'KIA',
    'Fixed deposit accounts',
    'Stratosphere',
    'Phone booth'
  ],
  [
    'Botanical gardens',
    'Knights',
    'Night soil',
    'Uganda Martyrs⁠⁠⁠⁠',
    'Adding machine'
  ],
  ['Good year', 'EAC', 'Big size', 'Florescent tubes', 'Mulwana empire'],
  [
    'Chair cushions',
    'Value added tax',
    'Pay as you earn',
    'Door knob',
    'Peter and Jane'
  ],
  [
    'Chief Executive officer',
    'Anger management',
    'The ministry of education',
    'Avocado',
    'Bed bugs'
  ],
  ['Web browser', 'Spock', 'King Kong', 'Jada Pinket', 'Salt bae'],
  [
    'Sugar daddies',
    'Kwagalana group',
    'Property agents',
    'Sportsbet',
    'Bonjour ( total shops)'
  ],
  [
    'USSR',
    'Cartoons',
    'Live stalk farming',
    'Sitting at the high table',
    'The French Revolution'
  ],
  [
    'Cassette tape',
    'Superman v Batman',
    'A Chariot',
    'Nakasongola',
    'Mutaasa Kafeero Plaza'
  ],
  ['Wolokoso', 'Heathens', 'The Haunted Hathaways', 'Watoto', 'Police pickup'],
  [
    'Igongo cultural centre',
    'Plastic smiles',
    'To engrave and embroid',
    'Uganda National Roads Authority',
    'Chikomando'
  ],
  [
    'Milkman',
    'Looney Tunes',
    'Fizzy drinks',
    'Chocolate syrup',
    'Arsene Wenger'
  ],
  [
    'White water rafting',
    'Bungee jumping',
    'Uganda Telecome',
    'Wallstreet',
    'Shau Khan'
  ],
  ['Brazilian hair', 'Grip gloves', 'Kanyamunyu', 'Noise proof', 'Maputo'],
  ['Baseball', 'Saala Puleesa', 'Sauti Sol', 'Vacuum cleaner', 'Allen Kagina'],
  [
    'Arnold Schwarzenegger',
    'Rift valley railway',
    'An Intranet',
    'Beautiful mess',
    'Nursing'
  ],
  ['Rice porridge', 'Fila', 'Telefunken', 'American pie', 'Checkers'],
  [' Cheops', 'Pirelli', 'Sugar cubes', 'To Expire', 'Bull shit'],
  [
    'Snap chat',
    'Sweat glands',
    'Barclays Bank',
    'Club silk',
    'Concentrate admixtures'
  ],
  ['Wheat grains', 'Cereal bowl', 'Mallet', 'Table mats', 'Salt shaker'],
  [
    'Reaching heights',
    'Shaka Zulu',
    'Honey combs',
    'Baakisiima dance',
    'Raka raka dance'
  ],
  [
    'Indian coolies',
    'Israel',
    'Rwakitura',
    'Laundry basket',
    'Water purification'
  ],
  [
    'Entebbe International Airport',
    'Jarvis',
    'conductor.',
    'Nancy Drew',
    'Mumbere'
  ],
  [
    'Cumlo-nimbus clouds',
    'Camouflage',
    'Jack fruit',
    'Julius Nyerere International Airport',
    "Kabaka's Lake"
  ],
  [
    'Bay watch',
    'The good the bad the ugly',
    'Life Buoy',
    'Ssanyu FM',
    'Napoleon Bonaparte'
  ],
  [
    'Samsung galaxy',
    'Studio apartment',
    'Music system',
    'Prado',
    'Courts of law'
  ],
  ['The Sun', 'Otafire', 'The Bistro', 'Nursery rhymes', 'The mummy returns'],
  [
    'Kajjansi clays',
    'Door mat',
    'Lex Luther',
    'Sleeping sickening',
    'Iron ore'
  ],
  ['Leverage', 'Mwana-mujimu', 'Kitugum', 'Nana hostel', 'Doctor'],
  [
    'Polar bears',
    'Plot number and block number',
    'Kony',
    'Sweat glands',
    'We Young Women and Men of Uganda'
  ],
  [
    'Animal hides',
    'State minister',
    'Kings of Leon',
    'Bujagali Falls',
    'A quality surveyor'
  ],
  [
    'Speed bumps',
    'Ugandan Potholes',
    'Porous borders',
    'Transgender',
    'Kibimba rice'
  ],
  ['Nakasero blood bank', 'Y2K', 'Shakira', 'Clark Kent', 'Joseph Mabirizi'],
  [
    'Tunisia',
    'Battery Low',
    'Woolworth',
    'Quality over quantity',
    "Okot p'Bitek"
  ],
  ['Huawei', 'Firebase', 'Milutin Sredojević']
];
