/*ts-lint disable*/

// this file is autogenerated

export default [
  ['Chlorine gas', 'The Beatles', 'cityoil', 'Mary Mary', 'Desire Luzinda'],
  ['PCB', 'American pie', 'Kevin Hart', 'Cassette tape', 'Kenya Airways'],
  [
    'The good the bad the ugly',
    'City Oilers',
    'Solex padlock',
    'Sunset beach',
    'Eiffel tower'
  ],
  ['Bachwezi ', 'Beside', 'Phablet', 'Apollo Hotel', 'Door knob'],
  ['Golola Moses', 'Fala', 'kalita', 'The DAB', 'Trevor Noah'],
  [
    'Muchomo',
    'The dictator',
    'Ekitobero a la carte (double check that spelling)',
    'Kawempe',
    'Baseball'
  ],
  ['Nairobi', 'Kiwi', 'The River Nile', 'Video Library', 'NBA'],
  ['atin paco', 'Dexters Lab', 'Capital Shoppers promotion', 'Game', 'cell'],
  ['Olduvai gorge', 'Piatto', 'Night dancers', 'Roofings', ' Nefertiti'],
  ['Nile Special', 'System unit', 'Poker face', 'Fraud', 'SGS'],
  ['Landline', 'Mallet', 'Graphite', 'Karamajong', 'Jinja Town'],
  [
    'Beauty and the Beast',
    'Bamuda triangle',
    'Dumpy level',
    'Chips and chaps',
    'slabs'
  ],
  ['Cheese bread', 'WWE', 'Joe Bidden', 'Tetris', 'Swimming pool'],
  ['300', ' General Biraro', 'Buganda', 'Records', 'Cereal bowl'],
  [
    'Andrew Mwenda',
    'UPDF Special Forces Command',
    'roof',
    'Wrestlemania',
    'Chuck Noris'
  ],
  ['Snowden', 'Mountain Gorilla', 'Nankasa dance', 'Red Indians', 'Vitruvius'],
  [
    'land lord',
    'Sese gateway Beach',
    'Kanyamunyu',
    'Fantastic Four',
    'Edward Kale Kayihura'
  ],
  [
    'Greenland Bank ',
    'Fela',
    'Tamale mirundi',
    'Agnes Nandutu',
    'Milton Obote'
  ],
  [
    'Masaka road',
    'Power horse',
    'Lohnro Motors',
    'Presidential handshake',
    'Dairy farming'
  ],
  ['Kiss of death', 'interior design', 'Eddie Kenzo', 'Nissan', 'VGA'],
  ['plan A', 'The golf course hotel', 'Facebook', 'Kobil', 'Acholi'],
  ['Wavah water', 'Mombasa', 'Nasser', 'The omega', 'The Black Mambas'],

];
